export const ROUTES = {
  home: "/",
  explore: "/explore",
  quiz: "/quiz",
  results: "/results",
  leaderboard: "/leaderboard",
  pricing: "/pricing",
  account: "/account",
  accountProfile: "/account/profile",
  missions: "/missions",
  achievements: "/achievements",
  wallet: "/wallet",
  referrals: "/referrals",
  billing: "/billing",
  paymentStatus: "/payment-status",
  practice: "/practice",
  quizBuilder: "/quiz/create",
  myQuizzes: "/my-quizzes",
  aiAssistant: "/ai-assistant",
  terms: "/terms",
  privacy: "/privacy",
  support: "/support",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminTopics: "/admin/learning/topics",
  adminQuizzes: "/admin/learning/quizzes",
  adminContent: "/admin/learning/content",
  adminQuestions: "/admin/learning/questions",
  adminRandomGenerator: "/admin/learning/random-generator",
  adminImportExport: "/admin/learning/import-export",
  adminPoints: "/admin/gamification/points",
  adminXp: "/admin/gamification/xp",
  adminGamification: "/admin/gamification",
  adminUsers: "/admin/users",
  adminUserGroups: "/admin/users/groups",
  adminErrors: "/admin/moderation/errors",
  adminAnalytics: "/admin/analytics",
  adminSeoPreview: "/admin/seo-preview",
  adminMonitoring: "/admin/system/monitoring",
  adminLogs: "/admin/system/logs",
  adminAi: "/admin/system/ai",
  adminTheme: "/admin/appearance/theme",
  adminSettings: "/admin/settings",
} as const;

export type RouteAccessPolicy = "public" | "authenticated" | "admin";
export type RoutePermission = "profile.view" | "learning.view" | "mission.view" | "achievement.view" | "point.view" | "point.topup" | "payment.view" | "payment.create" | "quiz.create" | "quiz.view" | "quiz.edit" | "result.view" | "ai.quiz.generate" | "admin.access";
export type RouteMeta = { access: RouteAccessPolicy; permission?: RoutePermission };

export const ROUTE_META: Partial<Record<(typeof ROUTES)[keyof typeof ROUTES], RouteMeta>> = {
  [ROUTES.account]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.accountProfile]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.missions]: { access: "authenticated", permission: "mission.view" },
  [ROUTES.achievements]: { access: "authenticated", permission: "achievement.view" },
  [ROUTES.wallet]: { access: "authenticated", permission: "point.view" },
  [ROUTES.referrals]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.billing]: { access: "authenticated", permission: "point.topup" },
  [ROUTES.paymentStatus]: { access: "authenticated", permission: "payment.view" },
  [ROUTES.practice]: { access: "authenticated", permission: "learning.view" },
  [ROUTES.quizBuilder]: { access: "authenticated", permission: "quiz.create" },
  [ROUTES.myQuizzes]: { access: "authenticated", permission: "quiz.view" },
  [ROUTES.aiAssistant]: { access: "authenticated", permission: "ai.quiz.generate" },
  [ROUTES.admin]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminDashboard]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminTopics]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminQuizzes]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminContent]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminQuestions]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminRandomGenerator]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminImportExport]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminPoints]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminXp]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminGamification]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminUsers]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminUserGroups]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminErrors]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminAnalytics]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminSeoPreview]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminMonitoring]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminLogs]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminAi]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminTheme]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminSettings]: { access: "admin", permission: "admin.access" },
};

export const LEGACY_ROUTE_MAP: Record<string, string> = {
  "/kham-pha": ROUTES.explore,
  "/bang-xep-hang": ROUTES.leaderboard,
  "/xep-hang": ROUTES.leaderboard,
  "/bang-gia": ROUTES.pricing,
  "/ho-so": ROUTES.account,
  "/nhiem-vu": ROUTES.missions,
  "/thanh-tich": ROUTES.achievements,
  "/vi": ROUTES.wallet,
  "/vi-point": ROUTES.wallet,
  "/gioi-thieu": ROUTES.referrals,
  "/nap-point": ROUTES.billing,
  "/thanh-toan": ROUTES.paymentStatus,
  "/luyen-tap": ROUTES.practice,
  "/tao-quiz": ROUTES.quizBuilder,
  "/quiz-cua-toi": ROUTES.myQuizzes,
  "/tro-ly-ai": ROUTES.aiAssistant,
  "/quan-tri": ROUTES.admin,
  "/quan-tri/chu-de": ROUTES.adminTopics,
  "/quan-tri/quiz-system": ROUTES.adminQuizzes,
  "/quan-tri/noi-dung": ROUTES.adminContent,
  "/quan-tri/cau-hoi": ROUTES.adminQuestions,
  "/quan-tri/tao-de-ngau-nhien": ROUTES.adminRandomGenerator,
  "/quan-tri/import-xuat": ROUTES.adminImportExport,
  "/quan-tri/nguoi-dung": ROUTES.adminUsers,
  "/quan-tri/nhom-nguoi-dung": ROUTES.adminUserGroups,
  "/quan-tri/point": ROUTES.adminPoints,
  "/quan-tri/xp": ROUTES.adminXp,
  "/quan-tri/gamification": ROUTES.adminGamification,
  "/quan-tri/bao-cao": ROUTES.adminAnalytics,
  "/quan-tri/live-monitoring": ROUTES.adminMonitoring,
  "/quan-tri/bao-loi": ROUTES.adminErrors,
  "/quan-tri/nhat-ky": ROUTES.adminLogs,
  "/quan-tri/thuong-hieu": ROUTES.adminTheme,
  "/quan-tri/ai-assistant": ROUTES.adminAi,
  "/quan-tri/cai-dat": ROUTES.adminSettings,
};
