export const ROUTES = {
  home: "/",
  explore: "/quiz",
  quiz: "/quiz",
  results: "/results",
  leaderboard: "/leaderboard",
  pricing: "/pricing",
  account: "/account",
  dashboard: "/dashboard",
  missions: "/missions",
  achievements: "/achievements",
  wallet: "/wallet",
  referrals: "/referrals",
  billing: "/billing",
  paymentStatus: "/payment-status",
  practice: "/practice",
  practiceReview: "/practice/review",
  quizBuilder: "/quiz/create",
  myQuizzes: "/my-quizzes",
  aiAssistant: "/ai-assistant",
  terms: "/terms",
  privacy: "/privacy",
  support: "/support",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminTopics: "/admin/learning/topics",
  adminQuizzes: "/admin/learning/quizzes",
  adminContent: "/admin/learning/content",
  adminQuestions: "/admin/learning/questions",
  adminRandomGenerator: "/admin/learning/random-generator",
  adminImportExport: "/admin/learning/import-export",
  adminPoints: "/admin/gamification/points",
  adminXp: "/admin/gamification/xp",
  adminGamification: "/admin/gamification",
  adminUsers: "/admin/users",
  adminUserGroups: "/admin/users/groups",
  adminErrors: "/admin/moderation/errors",
  adminAnalytics: "/admin/analytics",
  adminSeoPreview: "/admin/seo-preview",
  adminMonitoring: "/admin/system/monitoring",
  adminLogs: "/admin/system/logs",
  adminAi: "/admin/system/ai",
  adminTheme: "/admin/appearance/theme",
  adminSettings: "/admin/settings",
} as const;

export function getExploreTopicRoute(topicId?: number | null) {
  return topicId && topicId > 0
    ? `${ROUTES.explore}?topic=${encodeURIComponent(topicId)}`
    : ROUTES.explore;
}

export type RouteAccessPolicy = "public" | "authenticated" | "admin";
export type RoutePermission = "profile.view" | "learning.view" | "mission.view" | "achievement.view" | "point.view" | "point.topup" | "payment.view" | "payment.create" | "quiz.create" | "quiz.view" | "quiz.edit" | "result.view" | "ai.quiz.generate" | "admin.access";
export type RouteMeta = { access: RouteAccessPolicy; permission?: RoutePermission };

export const ROUTE_META: Partial<Record<(typeof ROUTES)[keyof typeof ROUTES], RouteMeta>> = {
  [ROUTES.account]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.dashboard]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.missions]: { access: "authenticated", permission: "mission.view" },
  [ROUTES.achievements]: { access: "authenticated", permission: "achievement.view" },
  [ROUTES.wallet]: { access: "authenticated", permission: "point.view" },
  [ROUTES.referrals]: { access: "authenticated", permission: "profile.view" },
  [ROUTES.billing]: { access: "authenticated", permission: "point.topup" },
  [ROUTES.paymentStatus]: { access: "authenticated", permission: "payment.view" },
  [ROUTES.practice]: { access: "authenticated", permission: "learning.view" },
  [ROUTES.quizBuilder]: { access: "authenticated", permission: "quiz.create" },
  [ROUTES.myQuizzes]: { access: "authenticated", permission: "quiz.view" },
  [ROUTES.aiAssistant]: { access: "authenticated", permission: "ai.quiz.generate" },
  [ROUTES.admin]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminDashboard]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminTopics]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminQuizzes]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminContent]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminQuestions]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminRandomGenerator]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminImportExport]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminPoints]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminXp]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminGamification]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminUsers]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminUserGroups]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminErrors]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminAnalytics]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminSeoPreview]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminMonitoring]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminLogs]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminAi]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminTheme]: { access: "admin", permission: "admin.access" },
  [ROUTES.adminSettings]: { access: "admin", permission: "admin.access" },
};
