import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Award, Crown, Medal, Target, Trophy } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const tabs = ["Mọi thời đại", "Tháng này", "Tuần này"];

export default function Leaderboard() {
  const [period, setPeriod] = useState(tabs[0]);
  const { data, isLoading } = trpc.leaderboard.list.useQuery();
  return <div className="min-h-screen bg-[#f6f5ef]"><SiteHeader />
    <main className="container py-12 lg:py-16"><section className="overflow-hidden rounded-[32px] bg-[#173a51] p-7 text-white shadow-[0_20px_50px_rgba(17,48,70,.18)] lg:p-11"><div className="relative z-10 max-w-xl"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#e4c77f]">Bảng xếp hạng</p><h1 className="mt-3 font-serif text-[42px] font-semibold tracking-[-.05em] sm:text-[55px]">Ghi nhận một hành trình bền bỉ.</h1><p className="mt-4 text-sm leading-6 text-[#c5d3d6]">Điểm số là dấu mốc để nhìn lại. Dshare tôn trọng việc học có mục tiêu và tinh thần tiến bộ đều đặn.</p></div><Trophy className="absolute right-[max(8%,calc((100%-1180px)/2))] top-28 hidden text-[#e4c77f]/20 lg:block" size={180} /></section>
      <section className="mt-9 grid gap-6 lg:grid-cols-[1fr_.32fr]"><div className="rounded-[28px] border border-[#17334a]/8 bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-[#17334a]/8 pb-5 sm:flex-row sm:items-center"><div><h2 className="font-serif text-[29px] font-semibold tracking-[-.035em] text-[#183a51]">Thành tích học tập</h2><p className="mt-1 text-xs text-[#6a7a83]">Xếp theo điểm cao nhất và số lượt hoàn thành.</p></div><div className="flex gap-1 rounded-full bg-[#f0f1ed] p-1">{tabs.map(tab => <button key={tab} onClick={() => setPeriod(tab)} className={`rounded-full px-3 py-2 text-[11px] font-semibold ${period === tab ? "bg-[#173a51] text-white" : "text-[#758187]"}`}>{tab}</button>)}</div></div>
        {isLoading ? <div className="py-16 text-center text-sm text-[#6a7a83]">Đang tải thành tích…</div> : data?.length ? <div className="divide-y divide-[#17334a]/7">{data.map((entry, index) => <div key={entry.userId} className="flex items-center gap-4 py-5"><span className={`grid h-9 w-9 place-items-center rounded-full font-serif text-lg font-bold ${index < 3 ? "bg-[#e8d49d] text-[#70521b]" : "bg-[#edf0ec] text-[#5e7078]"}`}>{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#25465b]">{entry.name ?? "Học viên Dshare"}</p><p className="mt-1 text-[11px] text-[#7d898d]">{entry.completedCount} lượt hoàn thành</p></div><p className="font-serif text-[23px] font-semibold text-[#183a51]">{entry.bestScore}<span className="ml-1 text-xs text-[#8a9598]">đ</span></p></div>)}</div> : <div className="py-14 text-center"><Award className="mx-auto text-[#c09b55]" size={28} /><h3 className="mt-4 font-serif text-2xl font-semibold text-[#183a51]">Bảng thành tích đang chờ dấu mốc đầu tiên</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#74818a]">Hoàn thành một bài kiểm tra để xuất hiện trong bảng xếp hạng của Dshare.</p><Button asChild className="mt-6 rounded-full bg-[#183a51]"><Link href="/kham-pha">Khám phá bộ đề</Link></Button></div>}</div>
        <aside className="rounded-[28px] bg-[#e9ddbd] p-6"><Crown className="text-[#9c7432]" size={23} /><p className="mt-6 text-[10px] font-bold uppercase tracking-[.17em] text-[#8b6b2e]">Cách ghi nhận</p><h2 className="mt-2 font-serif text-[28px] font-semibold leading-tight text-[#173a51]">Một cuộc đua với chính mình.</h2><div className="mt-7 space-y-5 text-xs leading-5 text-[#52625e]"><p><strong className="text-[#25465b]">Điểm cao nhất:</strong> Kết quả tốt nhất của mỗi học viên trong các lượt làm hợp lệ.</p><p><strong className="text-[#25465b]">Nhịp học:</strong> Các lượt hoàn thành giúp bạn duy trì sự nhất quán.</p><p><strong className="text-[#25465b]">Công bằng:</strong> Mỗi đề kiểm tra được xáo trộn cho từng lượt làm.</p></div><Medal className="mt-8 text-[#9c7432]" size={24} /></aside></section>
    </main>
  </div>;
}
