import AccountLayout from "@/components/AccountLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, Clock3, FileQuestion, Plus, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

type StatusFilter = "all" | "draft" | "published";

export default function MyQuizzes() {
  const [, setLocation] = useLocation();
  const [filter, setFilter] = useState<StatusFilter>("all");
  const quizzes = trpc.creator.myQuizzes.useQuery();
  const filtered = useMemo(() => (quizzes.data ?? []).filter(quiz => filter === "all" || (filter === "published" ? quiz.isPublished : !quiz.isPublished)), [filter, quizzes.data]);
  const publishedCount = (quizzes.data ?? []).filter(quiz => quiz.isPublished).length;
  const draftCount = (quizzes.data ?? []).filter(quiz => !quiz.isPublished).length;
  return <AccountLayout><main className="min-h-[calc(100vh-76px)] bg-[#f6f8fc] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-4 rounded-[26px] border border-[#172554]/10 bg-white p-5 shadow-[0_10px_30px_rgba(20,44,91,0.05)] sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#065be5]">Không gian sáng tạo</p><h1 className="mt-1 font-serif text-3xl font-semibold tracking-[-.035em] text-[#172554]">Quiz của tôi</h1><p className="mt-2 text-sm text-[#617786]">Quản lý các bộ câu hỏi bạn đã tạo và tiếp tục phát triển bản nháp.</p></div><Button type="button" onClick={() => setLocation("/tao-quiz")} className="h-11 rounded-xl bg-gradient-to-r from-[#065be5] to-[#3762d2] px-5 text-sm shadow-[0_10px_22px_rgba(6,91,229,.24)] hover:from-[#0451c9] hover:to-[#2c53bc]"><Plus size={17} />Tạo Quiz mới</Button></header><section className="mt-4 grid gap-3 sm:grid-cols-3"><StatCard label="Tổng Quiz" value={(quizzes.data ?? []).length} icon={BookOpenCheck} tone="bg-[#eef4ff] text-[#065be5]" /><StatCard label="Bản nháp" value={draftCount} icon={FileQuestion} tone="bg-[#fff8e8] text-[#b77900]" /><StatCard label="Đã xuất bản" value={publishedCount} icon={Sparkles} tone="bg-[#effcf6] text-[#007453]" /></section><section className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-[#172554]/10 bg-white p-1">{(["all", "draft", "published"] as StatusFilter[]).map(value => <button key={value} type="button" onClick={() => setFilter(value)} className={`rounded-lg px-3 py-2 text-xs font-bold transition ${filter === value ? "bg-[#172554] text-white" : "text-[#617786] hover:bg-[#eef4ff]"}`}>{value === "all" ? "Tất cả" : value === "draft" ? "Bản nháp" : "Đã xuất bản"}</button>)}</div><p className="text-xs text-[#71838d]">{filtered.length} Quiz hiển thị</p></div>{quizzes.isLoading ? <div className="mt-4 grid gap-4 md:grid-cols-2">{[1, 2, 3, 4].map(index => <div key={index} className="h-48 animate-pulse rounded-2xl bg-white" />)}</div> : filtered.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{filtered.map(quiz => <QuizCard key={quiz.id} quiz={quiz} onCreate={() => setLocation("/tao-quiz")} />)}</div> : <EmptyQuizzes filter={filter} onCreate={() => setLocation("/tao-quiz")} />}</section></div></main></AccountLayout>;
}

function StatCard({ label, value, icon: Icon, tone }: { label: string; value: number; icon: typeof BookOpenCheck; tone: string }) { return <article className="flex items-center gap-3 rounded-2xl border border-[#172554]/8 bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18} /></span><div><p className="text-xl font-bold text-[#172554]">{value}</p><p className="text-[11px] font-semibold text-[#71838d]">{label}</p></div></article>; }

function QuizCard({ quiz, onCreate }: { quiz: any; onCreate: () => void }) { const updatedAt = new Date(quiz.updatedAt); const isPublished = Boolean(quiz.isPublished); return <article className="overflow-hidden rounded-2xl border border-[#172554]/10 bg-white shadow-[0_10px_30px_rgba(20,44,91,0.04)]"><div className="relative h-28 bg-gradient-to-br from-[#eaf3ff] via-[#f7f4ff] to-[#e8fbf4]">{quiz.coverImageUrl ? <img src={quiz.coverImageUrl} alt="" className="h-full w-full object-cover" /> : <div className="absolute inset-0 grid place-items-center text-[#065be5]/35"><FileQuestion size={40} /></div>}<span className={`absolute right-3 top-3 rounded-full px-2.5 py-1 text-[10px] font-bold ${isPublished ? "bg-[#effcf6] text-[#007453]" : "bg-white/90 text-[#b77900]"}`}>{isPublished ? "Đã xuất bản" : "Bản nháp"}</span></div><div className="p-4"><h2 className="line-clamp-1 text-base font-bold text-[#172554]">{quiz.title}</h2><p className="mt-1 line-clamp-2 min-h-9 text-xs leading-5 text-[#71838d]">{quiz.summary || "Chưa có mô tả cho Quiz này."}</p><div className="mt-4 flex flex-wrap items-center gap-3 text-[11px] font-semibold text-[#617786]"><span className="inline-flex items-center gap-1"><FileQuestion size={13} className="text-[#065be5]" />{quiz.questionCount} câu hỏi</span><span className="inline-flex items-center gap-1"><Clock3 size={13} className="text-[#7057e8]" />{Math.max(1, Math.round((quiz.durationSeconds ?? 900) / 60))} phút</span><span className="ml-auto">Cập nhật {Number.isNaN(updatedAt.getTime()) ? "gần đây" : updatedAt.toLocaleDateString("vi-VN")}</span></div></div></article>; }

function EmptyQuizzes({ filter, onCreate }: { filter: StatusFilter; onCreate: () => void }) { return <div className="mt-4 rounded-[26px] border border-dashed border-[#065be5]/25 bg-white p-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eef4ff] text-[#065be5]"><FileQuestion size={22} /></span><h2 className="mt-4 text-lg font-bold text-[#172554]">{filter === "all" ? "Bạn chưa tạo Quiz nào" : "Chưa có Quiz phù hợp"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#71838d]">{filter === "all" ? "Bắt đầu tạo bộ câu hỏi đầu tiên để luyện tập hoặc chia sẻ với người học." : "Thử thay đổi bộ lọc hoặc tạo một Quiz mới."}</p><Button type="button" onClick={onCreate} className="mt-5 rounded-xl bg-[#065be5]"><Plus size={16} />Tạo Quiz mới</Button></div>; }
