import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Check } from "lucide-react";
import { Link } from "wouter";

const tierLabels = { basic: "Basic", pro: "PRO", premium: "PREMIUM" } as const;
const defaultBenefits = {
  basic: ["Làm Quiz cơ bản", "20 lượt làm/tháng", "Tạo 2 Quiz/tháng"],
  pro: ["Mở khóa nội dung PRO", "40 lượt làm/tháng", "Tạo 20 Quiz/tháng"],
  premium: ["Mở khóa toàn bộ nội dung", "Lượt làm không giới hạn", "Tạo 50 Quiz/tháng"],
} as const;
const formatVnd = (amount: number) => `${amount.toLocaleString("vi-VN")}đ`;

export default function Pricing() {
  const plans = trpc.catalog.membershipPlans.useQuery();
  return <div className="min-h-screen bg-white"><SiteHeader /><main className="container py-14 lg:py-20"><div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#065be5]">Gói học linh hoạt</p><h1 className="mt-3 font-serif text-[42px] font-semibold tracking-[-.05em] text-[#172554] sm:text-[50px]">Chọn Gói Phù Hợp Để Trải Nghiệm Toàn Diện Nhất</h1><p className="mt-4 text-sm leading-6 text-[#617786]">Thông tin gói, quyền lợi, giá và ưu đãi được cập nhật trực tiếp từ cấu hình quản trị.</p></div>
    {plans.isLoading ? <div className="mt-12 grid gap-5 lg:grid-cols-3">{[1, 2, 3].map(item => <div key={item} className="h-120 animate-pulse rounded-[29px] border border-[#172554]/8 bg-[#f7faff]" />)}</div> : plans.error ? <div role="alert" className="mx-auto mt-12 max-w-xl rounded-3xl bg-[#fff0f6] p-6 text-center text-sm text-[#de1264]">Không thể tải các gói đăng ký. Vui lòng thử lại sau.</div> : plans.data?.length ? <div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.data.map(plan => { const highlighted = plan.tier === "pro"; const displayPrice = plan.promoPrice ?? plan.monthlyPrice; const benefits = plan.benefits?.length ? plan.benefits : defaultBenefits[plan.tier]; return <article key={plan.id} className={`relative rounded-[29px] border p-7 ${highlighted ? "border-[#f59e0b] bg-[#172554] text-white shadow-[0_24px_50px_rgba(23,58,81,.18)]" : "border-[#172554]/10 bg-white text-[#172554]"}`}>{highlighted && <span className="absolute right-5 top-5 rounded-full bg-[#fbbf24] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#172554]">Khuyến nghị</span>}<p className={`text-[11px] font-bold uppercase tracking-[.17em] ${highlighted ? "text-[#fbbf24]" : "text-[#f59e0b]"}`}>{tierLabels[plan.tier]}</p><h2 className="mt-4 text-xl font-bold">{plan.name}</h2><p className={`mt-2 min-h-10 text-xs leading-5 ${highlighted ? "text-[#dbeafe]" : "text-[#617786]"}`}>{plan.description || "Gói học được cá nhân hóa theo nhu cầu của bạn."}</p><div className="mt-5 flex items-end gap-2"><p className="font-serif text-[38px] font-semibold">{formatVnd(displayPrice)}</p>{plan.tier !== "basic" ? <span className="mb-2 text-sm font-sans font-medium opacity-70">/ tháng</span> : null}</div>{plan.promoPrice !== null ? <p className={`mt-1 text-xs line-through ${highlighted ? "text-[#dbeafe]" : "text-[#71838d]"}`}>Giá gốc {formatVnd(plan.monthlyPrice)}</p> : <div className="mt-1 h-4" />}<div className={`my-7 h-px ${highlighted ? "bg-white/15" : "bg-[#172554]/10"}`} /><ul className="space-y-3">{benefits.map(benefit => <li key={benefit} className={`flex items-start gap-2 text-sm ${highlighted ? "text-[#eef4ff]" : "text-[#172554]"}`}><Check size={14} className={`mt-0.5 shrink-0 ${highlighted ? "text-[#fbbf24]" : "text-[#007453]"}`} strokeWidth={3} />{benefit}</li>)}</ul><Button asChild className={`mt-9 w-full rounded-full ${highlighted ? "bg-[#fbbf24] text-[#172554] hover:bg-[#fbbf24]" : "bg-[#eef4ff] text-[#172554] hover:bg-[#eef4ff]"}`}><Link href={`/nap-point?planTier=${plan.tier}`}>{plan.tier === "basic" ? "Khám phá miễn phí" : plan.payosEnabled ? "Nâng cấp qua PayOS" : "Xem thông tin gói"}</Link></Button></article>; })}</div> : <div role="status" className="mx-auto mt-12 max-w-xl rounded-3xl border border-[#172554]/10 bg-[#f7faff] p-8 text-center text-sm text-[#617786]">Hiện chưa có gói đăng ký nào đang hoạt động.</div>}
  </main></div>;
}
