import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { pricingPlans } from "@/data/demo";
import { Check, Info } from "lucide-react";
import { Link } from "wouter";

export default function Pricing() {
  return <div className="min-h-screen bg-[#fff7e6]"><SiteHeader />
    <main className="container py-14 lg:py-20"><div className="mx-auto max-w-2xl text-center"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#f59e0b]">Gói học linh hoạt</p><h1 className="mt-3 font-serif text-[43px] font-semibold tracking-[-.05em] text-[#172554] sm:text-[56px]">Chọn nhịp học phù hợp với mục tiêu của bạn.</h1><p className="mt-5 text-sm leading-6 text-[#617786]">Bạn có thể bắt đầu miễn phí, sau đó mở rộng quyền truy cập khi hành trình học cần nhiều chiều sâu hơn.</p></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-3">{pricingPlans.map(plan => <article key={plan.name} className={`relative rounded-[29px] border p-7 ${plan.highlighted ? "border-[#f59e0b] bg-[#172554] text-white shadow-[0_24px_50px_rgba(23,58,81,.18)]" : "border-[#172554]/10 bg-white text-[#172554]"}`}>{plan.highlighted && <span className="absolute right-5 top-5 rounded-full bg-[#fbbf24] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#172554]">Khuyến nghị</span>}<p className={`text-[11px] font-bold uppercase tracking-[.17em] ${plan.highlighted ? "text-[#fbbf24]" : "text-[#f59e0b]"}`}>{plan.name}</p><h2 className="mt-5 font-serif text-[38px] font-semibold">{plan.price}{plan.tier !== "Basic" && <span className="ml-1 text-sm font-sans font-medium opacity-70">/ tháng</span>}</h2><p className={`mt-3 min-h-10 text-sm leading-5 ${plan.highlighted ? "text-[#eef4ff]" : "text-[#617786]"}`}>{plan.description}</p><div className={`my-7 h-px ${plan.highlighted ? "bg-white/15" : "bg-[#172554]/10"}`} /><ul className="space-y-3">{plan.benefits.map(benefit => <li key={benefit.label} className={`flex items-center justify-between gap-3 text-sm ${plan.highlighted ? "text-[#eef4ff]" : "text-[#172554]"}`}><span className="flex items-center gap-2"><Check size={14} className={plan.highlighted ? "text-[#fbbf24]" : "text-[#2563eb]"} strokeWidth={3} />{benefit.label}</span><strong className={benefit.value === "Không" ? "opacity-45" : plan.highlighted ? "text-[#fbbf24]" : "text-[#2563eb]"}>{benefit.value}</strong></li>)}</ul><Button asChild className={`mt-9 w-full rounded-full ${plan.highlighted ? "bg-[#fbbf24] text-[#172554] hover:bg-[#fbbf24]" : "bg-[#eef4ff] text-[#172554] hover:bg-[#eef4ff]"}`}><Link href={`/nap-point?plan=${encodeURIComponent(plan.name)}`}>{plan.tier === "Basic" ? "Đang sử dụng" : "Nâng cấp ngay"}</Link></Button></article>)}</div>
      <div className="mx-auto mt-10 flex max-w-3xl gap-4 rounded-2xl border border-[#172554]/9 bg-[#fff7e6] p-5 text-xs leading-5 text-[#617786]"><Info className="shrink-0 text-[#f59e0b]" size={18} /><p><strong className="text-[#172554]">Point và thanh toán.</strong> Ví Point lưu lịch sử cộng/trừ khi làm bài, nhận thưởng hoặc nâng gói. Luồng thanh toán trực tuyến cần được chủ dự án kết nối với nhà cung cấp trước khi mở bán.</p></div>
    </main>
  </div>;
}
