import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { pricingPlans } from "@/data/demo";
import { Check, CreditCard, Info, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function Pricing() {
  return <div className="min-h-screen bg-[#fffdf8]"><SiteHeader />
    <main className="container py-14 lg:py-20"><div className="mx-auto max-w-2xl text-center"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#a37b3a]">Gói học linh hoạt</p><h1 className="mt-3 font-serif text-[43px] font-semibold tracking-[-.05em] text-[#173a51] sm:text-[56px]">Chọn nhịp học phù hợp với mục tiêu của bạn.</h1><p className="mt-5 text-sm leading-6 text-[#657580]">Bạn có thể bắt đầu miễn phí, sau đó mở rộng quyền truy cập khi hành trình học cần nhiều chiều sâu hơn.</p></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-3">{pricingPlans.map(plan => <article key={plan.name} className={`relative rounded-[29px] border p-7 ${plan.highlighted ? "border-[#c49947] bg-[#173a51] text-white shadow-[0_24px_50px_rgba(23,58,81,.18)]" : "border-[#17334a]/10 bg-white text-[#173a51]"}`}>{plan.highlighted && <span className="absolute right-5 top-5 rounded-full bg-[#e4c378] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#173a51]">Phù hợp nhất</span>}<p className={`text-[11px] font-bold uppercase tracking-[.17em] ${plan.highlighted ? "text-[#e4c378]" : "text-[#a37b3a]"}`}>{plan.name}</p><h2 className="mt-5 font-serif text-[38px] font-semibold">{plan.price}<span className="ml-1 text-sm font-sans font-medium opacity-70">/ tháng</span></h2><p className={`mt-3 min-h-10 text-sm leading-5 ${plan.highlighted ? "text-[#c6d5d7]" : "text-[#6d7c84]"}`}>{plan.description}</p><div className={`my-7 h-px ${plan.highlighted ? "bg-white/15" : "bg-[#17334a]/10"}`} /><ul className="space-y-3">{plan.features.map(feature => <li key={feature} className={`flex items-center gap-3 text-sm ${plan.highlighted ? "text-[#f0f5f4]" : "text-[#405865]"}`}><span className={`grid h-5 w-5 place-items-center rounded-full ${plan.highlighted ? "bg-[#e4c378] text-[#173a51]" : "bg-[#e6eee3] text-[#537352]"}`}><Check size={12} strokeWidth={3} /></span>{feature}</li>)}</ul><Button onClick={() => toast.info("Kết nối thanh toán", { description: "Tính năng thanh toán sẽ được kích hoạt sau khi cấu hình cổng Stripe của dự án." })} className={`mt-9 w-full rounded-full ${plan.highlighted ? "bg-[#e4c378] text-[#173a51] hover:bg-[#efd38f]" : "bg-[#edf0ec] text-[#173a51] hover:bg-[#e1e5df]"}`}>{plan.name === "Basic" ? "Bắt đầu miễn phí" : "Chọn gói này"}</Button></article>)}</div>
      <div className="mx-auto mt-10 flex max-w-3xl gap-4 rounded-2xl border border-[#17334a]/9 bg-[#f3f3ef] p-5 text-xs leading-5 text-[#68747c]"><Info className="shrink-0 text-[#a47b36]" size={18} /><p><strong className="text-[#3d535c]">Point và thanh toán.</strong> Ví Point lưu lịch sử cộng/trừ khi làm bài, nhận thưởng hoặc nâng gói. Luồng thanh toán trực tuyến cần được chủ dự án kết nối với nhà cung cấp trước khi mở bán.</p></div>
    </main>
  </div>;
}
