import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { progressPreview } from "@/data/demo";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, BookOpenCheck, CalendarDays, ChartNoAxesCombined, CircleDollarSign, Clock3, Crown, Gift, LogIn, Target, Trophy } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function Profile() {
  const { user, loading } = useAuth();
  const summary = trpc.learner.summary.useQuery(undefined, { enabled: Boolean(user) });
  const history = trpc.learner.history.useQuery(undefined, { enabled: Boolean(user) });
  const updateProfile = trpc.learner.updateProfile.useMutation({ onSuccess: () => { summary.refetch(); toast.success("Đã cập nhật hồ sơ học tập."); } });
  if (!loading && !user) return <div className="min-h-screen bg-[#fffdf8]"><SiteHeader /><main className="container grid min-h-[calc(100vh-76px)] place-items-center py-12"><div className="max-w-md rounded-[28px] border border-[#17334a]/10 bg-white p-8 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e9ddbd] text-[#9a7432]"><LogIn size={21} /></span><h1 className="mt-6 font-serif text-[34px] font-semibold tracking-[-.04em] text-[#173a51]">Không gian học tập của bạn</h1><p className="mt-3 text-sm leading-6 text-[#697982]">Đăng nhập để lưu kết quả, theo dõi tiến độ và quản lý ví Point cá nhân.</p><Button onClick={() => startLogin()} className="mt-7 rounded-full bg-[#173a51]">Đăng nhập để tiếp tục <ArrowRight size={15} /></Button></div></main></div>;
  const profile = summary.data?.profile;
  const stats = summary.data?.stats;
  return <div className="min-h-screen bg-[#f5f5ef]"><SiteHeader />
    <main className="container py-9 lg:py-12"><section className="overflow-hidden rounded-[30px] bg-[#173a51] p-6 text-white sm:p-8 lg:p-10"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div className="flex items-center gap-5"><div className="grid h-16 w-16 place-items-center rounded-[22px] bg-[#e5c981] font-serif text-2xl font-bold text-[#173a51]">{user?.name?.slice(0, 1).toUpperCase() ?? "D"}</div><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#e5c981]">Không gian học tập</p><h1 className="mt-1 font-serif text-[32px] font-semibold tracking-[-.04em]">{user?.name ?? "Học viên Dshare"}</h1><p className="mt-1 text-xs text-[#c3d1d4]">Thành viên {profile?.tier ?? "basic"} · Học với mục tiêu rõ ràng</p></div></div><Link href="/bang-gia" className="inline-flex items-center gap-2 text-xs font-bold text-[#e5c981]">Nâng cấp trải nghiệm <ArrowRight size={14} /></Link></div></section>
      <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={BookOpenCheck} label="Bài đã hoàn thành" value={stats?.completed ?? 0} suffix="bài" /><Metric icon={Target} label="Điểm trung bình" value={stats?.averageScore ?? 0} suffix="đ" /><Metric icon={Trophy} label="Bài đạt mục tiêu" value={stats?.passedCount ?? 0} suffix="bài" /></section>
      <details className="mt-6 rounded-[22px] border border-[#17334a]/9 bg-white p-5"><summary className="cursor-pointer text-sm font-bold text-[#294b60]">Thiết lập hồ sơ học tập</summary><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); updateProfile.mutate({ bio: String(form.get("bio") ?? ""), avatarUrl: String(form.get("avatarUrl") ?? "") }); }} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-[#61727b]">Ảnh đại diện (URL)<input name="avatarUrl" defaultValue={profile?.avatarUrl ?? ""} placeholder="https://..." className="mt-2 h-10 w-full rounded-md border border-[#17334a]/10 bg-[#f7f7f3] px-3 text-xs font-normal outline-none focus:border-[#b88f44]" /></label><label className="text-xs font-semibold text-[#61727b]">Giới thiệu bản thân<textarea name="bio" defaultValue={profile?.bio ?? ""} placeholder="Mục tiêu học tập của bạn…" className="mt-2 min-h-20 w-full resize-none rounded-md border border-[#17334a]/10 bg-[#f7f7f3] p-3 text-xs font-normal outline-none focus:border-[#b88f44]" /></label><Button disabled={updateProfile.isPending} className="w-fit rounded-full bg-[#173a51] text-xs">Lưu thiết lập</Button></form></details>
      <section className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[28px] border border-[#17334a]/9 bg-white p-6"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#9c783d]">Tiến độ theo môn học</p><h2 className="mt-2 font-serif text-[28px] font-semibold text-[#173a51]">Học đều, thấy rõ tiến bộ.</h2></div><ChartNoAxesCombined className="text-[#9c783d]" size={22} /></div><div className="mt-8 space-y-6">{progressPreview.map(item => <div key={item.label}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-[#385365]">{item.label}</span><span className="font-mono text-[#7f8990]">{item.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#edf0ec]"><div className="h-full rounded-full" style={{ width: `${item.value}%`, backgroundColor: item.accent }} /></div></div>)}</div><Button asChild variant="outline" className="mt-8 rounded-full"><Link href="/kham-pha">Tiếp tục lộ trình <ArrowRight size={14} /></Link></Button></div>
        <div className="rounded-[28px] bg-[#e9ddbd] p-6"><CircleDollarSign className="text-[#92702f]" size={23} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.17em] text-[#8b6b2e]">Ví Point</p><p className="mt-2 font-serif text-[44px] font-semibold tracking-[-.05em] text-[#173a51]">{profile?.pointBalance ?? 0}</p><p className="text-xs text-[#6d6657]">Point khả dụng</p><div className="mt-6 rounded-2xl bg-white/45 p-4 text-xs leading-5 text-[#5c635e]"><Gift className="mb-2 text-[#9a7432]" size={16} />Nhận Point khi hoàn thành bài kiểm tra đạt mục tiêu hoặc khi báo lỗi câu hỏi được duyệt.</div><Button asChild className="mt-5 w-full rounded-full bg-[#173a51]"><Link href="/bang-gia">Nạp Point & nâng gói</Link></Button></div></section>
      <section className="mt-6 rounded-[28px] border border-[#17334a]/9 bg-white p-6"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#9c783d]">Lịch sử làm bài</p><h2 className="mt-2 font-serif text-[28px] font-semibold text-[#173a51]">Dấu mốc gần đây</h2></div><CalendarDays className="text-[#9c783d]" size={21} /></div>{history.data?.length ? <div className="mt-6 divide-y divide-[#17334a]/8">{history.data.map(item => <div key={item.attempt.id} className="flex flex-wrap items-center gap-4 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eff2ed] text-[#496b58]"><Clock3 size={16} /></span><div className="min-w-40 flex-1"><p className="text-sm font-semibold text-[#294b60]">{item.quizTitle}</p><p className="mt-1 text-[11px] text-[#78858a]">{item.quizMode === "testing" ? "Kiểm tra" : "Ôn tập"} · {item.attempt.completedAt?.toLocaleDateString("vi-VN")}</p></div><p className="font-serif text-2xl font-semibold text-[#173a51]">{item.attempt.score}đ</p></div>)}</div> : <div className="mt-6 rounded-2xl bg-[#f3f4f0] p-6 text-sm text-[#667782]">Bạn chưa có lượt làm bài được lưu. Hãy chọn một bộ đề để bắt đầu hành trình học tập.</div>}</section>
    </main>
  </div>;
}

function Metric({ icon: Icon, label, value, suffix }: { icon: typeof Target; label: string; value: number; suffix: string }) { return <div className="rounded-[22px] border border-[#17334a]/8 bg-white p-5"><Icon size={18} className="text-[#a37b3a]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#7d888c]">{label}</p><p className="mt-1 font-serif text-[30px] font-semibold text-[#173a51]">{value}<span className="ml-1 text-xs font-sans font-medium text-[#7c8588]">{suffix}</span></p></div>; }
