import { useAuth } from "@/_core/hooks/useAuth";
import AccountLayout from "@/components/AccountLayout";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { sharedDataQueryOptions } from "@/lib/sharedDataSync";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Award, BellRing, BookOpenCheck, CalendarDays, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Copy, Crown, Flame, Gift, GraduationCap, LogIn, Medal, PencilLine, ShieldCheck, Sparkles, Target, Trophy, UsersRound, WalletCards } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const preferenceLabels = [["studyReminders", "Nhắc học", "Gợi nhắc duy trì nhịp học"], ["resultUpdates", "Kết quả bài làm", "Điểm số và lời giải sau khi nộp"], ["platformUpdates", "Cập nhật nền tảng", "Tính năng và nội dung mới"]] as const;
const tierLabel: Record<string, string> = { basic: "Basic", pro: "Pro", premium: "Premium" };
const missionLabel: Record<string, string> = { daily: "Hôm nay", weekly: "Tuần này", special: "Chiến dịch" };

function formatNumber(value: number) { return Number(value ?? 0).toLocaleString("vi-VN"); }
function formatStudyDate(value: Date | null | undefined) { return value ? new Date(value).toLocaleDateString("vi-VN", { day: "2-digit", month: "short", year: "numeric" }) : "Đang cập nhật"; }

export default function Profile() {
  const { user, loading } = useAuth();
  const summary = trpc.learner.summary.useQuery(undefined, { enabled: Boolean(user), ...sharedDataQueryOptions });
  const history = trpc.learner.history.useQuery(undefined, { enabled: Boolean(user), ...sharedDataQueryOptions });
  const gamification = trpc.learner.gamification.useQuery(undefined, { enabled: Boolean(user), ...sharedDataQueryOptions });
  const leaderboard = trpc.leaderboard.xp.useQuery({ period: "week" }, { enabled: Boolean(user), ...sharedDataQueryOptions });
  const referral = trpc.learner.referral.useQuery(undefined, { enabled: Boolean(user), ...sharedDataQueryOptions });
  const updateProfile = trpc.learner.updateProfile.useMutation({ onSuccess: () => { summary.refetch(); toast.success("Đã cập nhật hồ sơ học tập."); }, onError: error => toast.error("Không thể lưu hồ sơ", { description: error.message }) });
  const [copied, setCopied] = useState(false);

  if (loading) return <ProfileShell><ProfileLoadingState label="Đang mở trung tâm học tập…" /></ProfileShell>;
  if (!user) return <ProfileShell><SignInState /></ProfileShell>;
  if (summary.isLoading) return <ProfileShell><ProfileLoadingState label="Đang đồng bộ hành trình học tập…" /></ProfileShell>;
  if (summary.error || !summary.data) return <ProfileShell><ProfileErrorState message={summary.error?.message} onRetry={() => summary.refetch()} /></ProfileShell>;

  const { profile, stats } = summary.data;
  const game = gamification.data;
  const currentLevel = game?.currentLevel;
  const nextLevel = game?.nextLevel;
  const xpBalance = profile.xpBalance ?? 0;
  const levelFloor = currentLevel?.minXp ?? 0;
  const levelTarget = nextLevel?.minXp ?? Math.max(levelFloor, xpBalance);
  const xpProgress = nextLevel ? Math.min(100, Math.max(0, Math.round(((xpBalance - levelFloor) / Math.max(1, levelTarget - levelFloor)) * 100))) : 100;
  const missions = (game?.missions ?? []) as any[];
  const missionDone = missions.filter(item => item.assignment.status === "claimed").length;
  const achievements = (game?.achievements ?? []) as any[];
  const badges = (game?.badges ?? []) as any[];
  const unlockedAchievements = achievements.filter(item => item.userAchievement.status === "unlocked").length;
  const completionRate = stats.completed ? Math.round((stats.passedCount / stats.completed) * 100) : 0;
  const xpByAttempt = new Map(((game?.xpHistory ?? []) as any[]).filter(item => item.sourceType === "attempt").map(item => [String(item.sourceId), item.amount]));
  const rankings = (leaderboard.data ?? []) as any[];
  const ownRank = rankings.findIndex(item => item.userId === user.id) + 1;
  const referralData = referral.data as any;
  const profileKey = `${profile.avatarUrl ?? ""}-${profile.learningGoal ?? ""}-${profile.updatedAt ?? ""}`;

  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    updateProfile.mutate({ avatarUrl: String(form.get("avatarUrl") ?? ""), bio: String(form.get("bio") ?? ""), learningGoal: String(form.get("learningGoal") ?? ""), notificationPreferences: { studyReminders: form.get("studyReminders") === "on", resultUpdates: form.get("resultUpdates") === "on", platformUpdates: form.get("platformUpdates") === "on" } });
  };
  const copyReferral = async () => {
    if (!referralData?.referralCode) return;
    try { await navigator.clipboard.writeText(referralData.referralCode); setCopied(true); toast.success("Đã sao chép mã giới thiệu."); window.setTimeout(() => setCopied(false), 1800); }
    catch { toast.error("Không thể sao chép mã", { description: "Hãy thử sao chép lại." }); }
  };

  return <ProfileShell><main className="container profile-workspace py-6 sm:py-8 lg:py-10">
    <section className="relative overflow-hidden rounded-[28px] border border-primary/12 bg-[radial-gradient(circle_at_89%_8%,rgba(255,255,255,.3),transparent_24%),linear-gradient(118deg,#0c4bbd_0%,#2563eb_57%,#6d4ce5_100%)] p-5 text-white shadow-[0_20px_48px_rgba(30,64,175,.2)] sm:p-7 lg:p-9">
      <div aria-hidden="true" className="absolute -right-16 -top-20 size-64 rounded-full border border-white/15 bg-white/5" /><div aria-hidden="true" className="absolute -bottom-24 right-1/3 size-52 rounded-full border border-white/10 bg-white/5" />
      <div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-4 sm:gap-5"><ProfileAvatar name={user.name ?? "Học viên Dshare"} src={profile.avatarUrl} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-white/20 bg-white/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.14em]">Hành trình học tập</span><span className="rounded-full border border-white/15 bg-white/8 px-2.5 py-1 text-[10px] font-bold">{tierLabel[profile.tier] ?? profile.tier}</span></div><h1 className="mt-2 truncate text-2xl font-black tracking-[-.045em] sm:text-3xl">{user.name ?? "Học viên Dshare"}</h1><p className="mt-1 text-sm font-semibold text-white/85">Level {currentLevel?.displayOrder ?? 1} · {currentLevel?.name ?? "Beginner"}</p><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">{profile.learningGoal || "Thiết lập mục tiêu học tập để Dshare đồng hành cùng hành trình của bạn."}</p></div></div><div className="w-full max-w-md rounded-[20px] border border-white/15 bg-white/10 p-4 backdrop-blur-sm"><div className="flex items-center justify-between text-[11px] font-bold"><span>LEVEL {currentLevel?.displayOrder ?? 1}</span><span>{nextLevel ? `LEVEL ${nextLevel.displayOrder}` : "MAX LEVEL"}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-white/15" role="progressbar" aria-label="Tiến độ XP tới Level tiếp theo" aria-valuemin={0} aria-valuemax={100} aria-valuenow={xpProgress}><div className="h-full rounded-full bg-[linear-gradient(90deg,#f9d44e,#f2a9ff)] transition-[width] duration-500 motion-reduce:transition-none" style={{ width: `${xpProgress}%` }} /></div><div className="mt-3 flex items-center justify-between gap-3 text-xs"><strong>{formatNumber(xpBalance)} XP</strong><span className="text-right text-white/75">{nextLevel ? `Còn ${formatNumber(game?.xpToNextLevel ?? 0)} XP để lên ${nextLevel.name}` : "Bạn đã chạm mốc cao nhất"}</span></div></div></div>
    </section>

    <section aria-label="Chỉ số học tập" className="mt-5 grid gap-3 sm:grid-cols-3"><DashboardStat icon={WalletCards} label="Point" value={formatNumber(profile.pointBalance)} note="Sẵn sàng dùng dịch vụ premium" href="/wallet" action="Mở ví" /><DashboardStat icon={Sparkles} label="Tổng XP" value={formatNumber(xpBalance)} note={nextLevel ? `Còn ${formatNumber(game?.xpToNextLevel ?? 0)} XP tới Level ${nextLevel.displayOrder}` : "Đã đạt cấp độ cao nhất"} href="/achievements" action="Xem tiến trình" tone="violet" /><DashboardStat icon={Award} label="Danh hiệu" value={formatNumber(unlockedAchievements || badges.length)} note={`${badges.length} huy hiệu đã được ghi nhận`} href="/achievements" action="Xem tất cả" tone="amber" /></section>

    <section className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-[24px] border border-border bg-surface p-5 shadow-[var(--shadow-sm)] sm:p-6"><SectionHeader eyebrow="Bảng xếp hạng" title="Vị trí của bạn" icon={Crown} actionHref="/leaderboard" action="Xem tất cả" /><div className="mt-5 space-y-3">{leaderboard.isLoading ? <BlockLoading label="Đang cập nhật bảng xếp hạng…" /> : leaderboard.error ? <BlockError label="Chưa tải được bảng xếp hạng" onRetry={() => leaderboard.refetch()} /> : rankings.length ? <>{rankings.slice(0, 3).map((entry, index) => <RankRow key={entry.userId} rank={index + 1} name={entry.name ?? "Học viên Dshare"} subtitle={entry.levelName ?? "Beginner"} xp={entry.xp ?? 0} />)}{ownRank > 3 ? <><div className="border-t border-dashed border-border-light" /><RankRow rank={ownRank} name="Bạn" subtitle={currentLevel?.name ?? "Beginner"} xp={xpBalance} active /></> : null}</> : <DashboardEmpty icon={Trophy} title="Bảng xếp hạng đang chờ dấu mốc đầu tiên" text="Hoàn thành Quiz để bắt đầu hành trình cạnh tranh lành mạnh." />}</div></section>
      <section className="rounded-[24px] border border-primary/12 bg-[linear-gradient(145deg,#f7fbff,#f4f0ff)] p-5 shadow-[var(--shadow-sm)] sm:p-6"><SectionHeader eyebrow="Giới thiệu bạn bè" title="Cùng học, cùng nhận thưởng" icon={UsersRound} actionHref="/referrals" action="Quản lý" /><p className="mt-3 text-sm leading-6 text-text-secondary">Mời bạn bè tham gia để cùng duy trì động lực học tập và nhận Point khi giới thiệu được ghi nhận.</p>{referral.isLoading ? <BlockLoading label="Đang tải mã giới thiệu…" /> : referral.error ? <BlockError label="Chưa tải được dữ liệu giới thiệu" onRetry={() => referral.refetch()} /> : <><div className="mt-5 flex items-center gap-2 rounded-[var(--radius-md-token)] border border-primary/15 bg-surface p-3"><code className="min-w-0 flex-1 truncate text-sm font-extrabold tracking-[.14em] text-primary">{referralData?.referralCode ?? "Đang chuẩn bị mã"}</code><Button size="sm" variant="outline" onClick={copyReferral} disabled={!referralData?.referralCode} className="shrink-0 rounded-full">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Đã sao chép" : "Sao chép"}</Button></div><div className="mt-4 grid grid-cols-2 gap-3"><MiniValue label="Bạn đã mời" value={`${referralData?.invitations?.length ?? 0} người`} /><MiniValue label="Thưởng đã nhận" value={`${formatNumber(referralData?.totalRewarded ?? 0)} Point`} /></div></>}</section></section>

    <section className="mt-5 rounded-[24px] border border-border bg-surface p-5 shadow-[var(--shadow-sm)] sm:p-6"><SectionHeader eyebrow="Nhiệm vụ" title="Nhiệm vụ đang chờ bạn" icon={Target} actionHref="/missions" action="Xem tất cả" /><div className="mt-5 grid gap-3 lg:grid-cols-3">{missions.length ? missions.slice(0, 3).map(item => <QuestItem key={item.assignment.id} item={item} />) : <div className="lg:col-span-3"><DashboardEmpty icon={Target} title="Chưa có nhiệm vụ phù hợp" text="Nhiệm vụ mới sẽ xuất hiện theo nhịp học và chiến dịch hiện hành." /></div>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-[var(--radius-md-token)] bg-muted/70 px-4 py-3 text-xs"><span className="text-text-secondary">Đã hoàn thành <strong className="text-foreground">{missionDone}/{missions.length}</strong> nhiệm vụ khả dụng.</span><Link href="/missions" className="inline-flex items-center gap-1 font-bold text-primary hover:underline">Khám phá nhiệm vụ <ArrowRight size={13} /></Link></div></section>

    <section className="mt-5 rounded-[24px] border border-border bg-surface p-5 shadow-[var(--shadow-sm)] sm:p-6"><SectionHeader eyebrow="Thành tích" title="Tủ danh hiệu của bạn" icon={Medal} actionHref="/achievements" action="Xem tất cả" /><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{achievements.length ? achievements.slice(0, 4).map(item => <AchievementPreview key={item.userAchievement.id} item={item} />) : <div className="col-span-full"><DashboardEmpty icon={Award} title="Thành tích đang chờ được chinh phục" text="Hoàn thành Quiz và nhiệm vụ để mở khóa dấu mốc đầu tiên." /></div>}</div></section>

    <section className="mt-5 rounded-[24px] border border-border bg-surface p-5 shadow-[var(--shadow-sm)] sm:p-6"><SectionHeader eyebrow="Bài Quiz đã làm" title="Hoạt động gần đây" icon={BookOpenCheck} actionHref="/explore" action="Làm Quiz" />{history.isLoading ? <BlockLoading label="Đang tải lịch sử làm bài…" /> : history.error ? <BlockError label="Chưa tải được lịch sử" onRetry={() => history.refetch()} /> : history.data?.length ? <div className="mt-4 divide-y divide-border-light">{history.data.slice(0, 5).map(item => <article key={item.attempt.id} className="flex flex-wrap items-center gap-3 py-4 first:pt-1"><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Clock3 size={17} /></span><div className="min-w-[12rem] flex-1"><p className="text-sm font-bold text-foreground">{item.quizTitle}</p><p className="mt-1 text-[11px] text-text-muted">{item.quizMode === "testing" ? "Kiểm tra" : "Ôn tập"} · {formatStudyDate(item.attempt.completedAt)}</p></div><div className="flex items-center gap-4 text-right"><div><p className="text-lg font-black tracking-[-.04em] text-foreground">{item.attempt.score ?? 0}<span className="ml-0.5 text-xs font-semibold text-text-muted">đ</span></p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-success">Đã ghi nhận</p></div>{xpByAttempt.get(String(item.attempt.id)) ? <span className="rounded-full bg-violet-500/10 px-2.5 py-1 text-[10px] font-bold text-violet-700">+{formatNumber(xpByAttempt.get(String(item.attempt.id)))} XP</span> : null}</div></article>)}</div> : <EmptyActivity />}</section>

    <details id="thiet-lap" className="group mt-5 scroll-mt-24 rounded-[24px] border border-border bg-surface shadow-[var(--shadow-sm)]" key={profileKey}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 sm:p-6"><span><span className="inline-flex items-center gap-2 text-sm font-bold text-foreground"><PencilLine size={16} className="text-primary" />Thiết lập hồ sơ & thông báo</span><span className="mt-1 block text-xs leading-5 text-text-secondary">Cập nhật ảnh đại diện, mục tiêu học tập và kênh thông báo của bạn.</span></span><ChevronDown className="shrink-0 text-text-muted transition-transform duration-200 group-open:rotate-180" size={19} /></summary><form onSubmit={submit} className="border-t border-border-light p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Ảnh đại diện (URL)" description="Dùng liên kết ảnh HTTPS để hiển thị ảnh cá nhân."><input id="avatarUrl" name="avatarUrl" type="url" defaultValue={profile.avatarUrl ?? ""} placeholder="https://..." className="field" /></Field><Field label="Mục tiêu học tập" description="Tối đa 220 ký tự, hiển thị trên Dashboard."><input id="learningGoal" name="learningGoal" defaultValue={profile.learningGoal ?? ""} maxLength={220} placeholder="Ví dụ: Đạt 7.0 IELTS trong 12 tuần" className="field" /></Field><Field label="Giới thiệu bản thân" full description="Một vài dòng về điều bạn muốn chinh phục."><textarea id="bio" name="bio" defaultValue={profile.bio ?? ""} maxLength={500} placeholder="Mục tiêu học tập hoặc điều bạn muốn chinh phục…" className="field min-h-28 resize-y" /></Field></div><fieldset className="mt-5 rounded-[var(--radius-lg-token)] border border-border-light bg-muted/65 p-4"><legend className="px-1 text-xs font-bold text-foreground"><BellRing className="mr-1 inline-block text-primary" size={14} />Tùy chọn nhận thông báo</legend><div className="mt-3 grid gap-3 md:grid-cols-3">{preferenceLabels.map(([name, title, note]) => <label key={name} className="flex cursor-pointer gap-3 rounded-[var(--radius-md-token)] border border-border-light bg-surface p-3 text-xs transition-colors hover:border-primary/25"><input name={name} type="checkbox" defaultChecked={profile.notificationPreferences?.[name] ?? true} className="mt-0.5 size-4 accent-primary" /><span><strong className="text-foreground">{title}</strong><span className="mt-1 block leading-4 text-text-muted">{note}</span></span></label>)}</div></fieldset><div className="mt-5 flex flex-wrap items-center gap-3"><Button disabled={updateProfile.isPending} className="rounded-full">{updateProfile.isPending ? "Đang lưu thay đổi…" : "Lưu thiết lập"}</Button><p className="text-xs text-text-muted">Các thay đổi chỉ có hiệu lực sau khi lưu.</p></div></form></details>
  </main></ProfileShell>;
}

function ProfileShell({ children }: { children: React.ReactNode }) { return <AccountLayout>{children}</AccountLayout>; }
function ProfileAvatar({ name, src }: { name: string; src?: string | null }) { const [failed, setFailed] = useState(false); const initial = name.trim().slice(0, 1).toUpperCase() || "D"; return <span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-white/30 bg-white/15 text-2xl font-black text-white shadow-[0_10px_22px_rgba(0,0,0,.14)] sm:size-20">{src && !failed ? <img src={src} alt={`Ảnh đại diện của ${name}`} className="size-full object-cover" onError={() => setFailed(true)} /> : initial}</span>; }
function DashboardStat({ icon: Icon, label, value, note, href, action, tone = "blue" }: { icon: typeof Target; label: string; value: string; note: string; href: string; action: string; tone?: "blue" | "violet" | "amber" }) { const styles = tone === "violet" ? "bg-violet-500/10 text-violet-700" : tone === "amber" ? "bg-amber-500/10 text-amber-700" : "bg-primary-light text-primary"; return <article className="rounded-[20px] border border-border bg-surface p-4 shadow-[var(--shadow-sm)]"><span className={`grid size-9 place-items-center rounded-[var(--radius-md-token)] ${styles}`}><Icon size={17} /></span><p className="mt-4 text-[10px] font-bold uppercase tracking-[.14em] text-text-muted">{label}</p><p className="mt-1 text-3xl font-black tracking-[-.05em] text-foreground">{value}</p><p className="mt-2 min-h-8 text-[11px] leading-4 text-text-secondary">{note}</p><Link href={href} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">{action} <ArrowRight size={13} /></Link></article>; }
function SectionHeader({ eyebrow, title, icon: Icon, actionHref, action }: { eyebrow: string; title: string; icon: typeof Target; actionHref: string; action: string }) { return <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">{eyebrow}</p><h2 className="mt-1 text-xl font-black tracking-[-.035em] text-foreground sm:text-2xl">{title}</h2></div><Link href={actionHref} className="inline-flex shrink-0 items-center gap-1 text-xs font-bold text-primary hover:underline">{action} <ArrowRight size={13} /></Link></div>; }
function RankRow({ rank, name, subtitle, xp, active }: { rank: number; name: string; subtitle: string; xp: number; active?: boolean }) { const icon = rank === 1 ? <Trophy size={15} /> : rank === 2 ? <Medal size={15} /> : rank === 3 ? <Award size={15} /> : rank; return <div className={`flex items-center gap-3 rounded-[var(--radius-md-token)] p-3 ${active ? "bg-primary-light" : "bg-background"}`}><span className={`grid size-8 shrink-0 place-items-center rounded-full text-xs font-bold ${rank <= 3 ? "bg-warning/14 text-warning" : "bg-muted text-text-secondary"}`}>{icon}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-foreground">{name}</p><p className="mt-0.5 text-[11px] text-text-muted">{subtitle}</p></div><strong className="text-sm text-foreground">{formatNumber(xp)} <span className="text-[10px] text-text-muted">XP</span></strong></div>; }
function QuestItem({ item }: { item: any }) { const percent = Math.min(100, Math.round((item.assignment.progress / Math.max(1, item.assignment.target)) * 100)); const done = item.assignment.status === "claimed" || item.assignment.status === "completed"; return <article className="rounded-[var(--radius-lg-token)] border border-border-light bg-background p-4"><div className="flex items-start gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full ${done ? "bg-success/10 text-success" : item.definition.repeatType === "special" ? "bg-violet-500/10 text-violet-700" : "bg-primary-light text-primary"}`}>{done ? <CheckCircle2 size={17} /> : item.definition.repeatType === "special" ? <Sparkles size={17} /> : <Target size={17} />}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-text-muted">{missionLabel[item.definition.repeatType] ?? "Nhiệm vụ"}</p><h3 className="mt-1 text-sm font-bold text-foreground">{item.definition.title}</h3></div><span className="shrink-0 rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-bold text-amber-700">+{formatNumber(item.assignment.xpReward)} XP</span></div><div className="mt-3 flex items-center gap-2"><div className="h-1.5 min-w-0 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[linear-gradient(90deg,var(--primary),#8b5cf6)]" style={{ width: `${percent}%` }} /></div><span className="shrink-0 text-[10px] font-bold text-text-secondary">{item.assignment.progress}/{item.assignment.target}</span></div>{done ? <p className="mt-2 text-[10px] font-bold text-success">Đã hoàn thành</p> : null}</div></div></article>; }
function AchievementPreview({ item }: { item: any }) { const unlocked = item.userAchievement.status === "unlocked"; const title = item.achievement.title ?? item.badge?.name ?? "Thành tích"; return <article className={`rounded-[var(--radius-lg-token)] border p-4 text-center ${unlocked ? "border-primary/15 bg-primary-light/45" : "border-border-light bg-muted/45 opacity-75"}`}><span className={`mx-auto grid size-11 place-items-center rounded-full ${unlocked ? "bg-surface text-primary shadow-sm" : "bg-muted text-text-muted"}`}>{unlocked ? <Award size={21} /> : <ShieldCheck size={20} />}</span><h3 className="mt-3 line-clamp-1 text-sm font-bold text-foreground">{title}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-text-secondary">{item.achievement.description ?? (unlocked ? "Đã mở khóa" : "Tiếp tục học để mở khóa")}</p></article>; }
function MiniValue({ label, value }: { label: string; value: string }) { return <div className="rounded-[var(--radius-md-token)] border border-border-light bg-surface p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-text-muted">{label}</p><p className="mt-1 text-sm font-bold text-foreground">{value}</p></div>; }
function BlockLoading({ label }: { label: string }) { return <p role="status" className="mt-5 rounded-[var(--radius-md-token)] bg-muted/65 p-4 text-sm text-text-secondary">{label}</p>; }
function BlockError({ label, onRetry }: { label: string; onRetry: () => void }) { return <div role="alert" className="mt-5 rounded-[var(--radius-md-token)] border border-danger/15 bg-danger/5 p-4"><p className="text-sm font-bold text-danger">{label}</p><Button variant="outline" onClick={onRetry} className="mt-3 h-8 rounded-full px-3 text-xs">Thử lại</Button></div>; }
function DashboardEmpty({ icon: Icon, title, text }: { icon: typeof Target; title: string; text: string }) { return <div className="rounded-[var(--radius-lg-token)] border border-dashed border-border bg-muted/50 p-6 text-center"><Icon className="mx-auto text-primary" size={22} /><p className="mt-3 text-sm font-bold text-foreground">{title}</p><p className="mx-auto mt-1 max-w-md text-xs leading-5 text-text-secondary">{text}</p></div>; }
function SignInState() { return <main className="container grid min-h-[calc(100vh-76px)] place-items-center py-12"><section className="max-w-md rounded-[28px] border border-border bg-surface p-8 text-center shadow-[var(--shadow-md)]"><span className="mx-auto grid size-12 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><LogIn size={21} /></span><h1 className="mt-6 text-3xl font-black tracking-[-.04em] text-foreground">Trung tâm học tập của bạn</h1><p className="mt-3 text-sm leading-6 text-text-secondary">Đăng nhập để lưu kết quả, theo dõi tiến độ và quản lý hành trình học tập cá nhân.</p><Button onClick={() => startLogin()} className="mt-7 rounded-full">Đăng nhập để tiếp tục <ArrowRight size={15} /></Button></section></main>; }
function ProfileLoadingState({ label }: { label: string }) { return <main className="container py-8"><section className="animate-pulse rounded-[28px] bg-muted/70 p-7 sm:p-9"><p role="status" aria-live="polite" className="text-sm font-medium text-text-secondary">{label}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><span className="h-24 rounded-[var(--radius-lg-token)] bg-surface/80" /><span className="h-24 rounded-[var(--radius-lg-token)] bg-surface/80" /><span className="h-24 rounded-[var(--radius-lg-token)] bg-surface/80" /></div></section></main>; }
function ProfileErrorState({ message, onRetry }: { message?: string; onRetry: () => void }) { return <main className="container grid min-h-[70vh] place-items-center py-12"><section className="max-w-md rounded-[var(--radius-xl-token)] border border-danger/20 bg-surface p-8 text-center shadow-[var(--shadow-sm)]"><h1 className="text-2xl font-black text-foreground">Chưa tải được Dashboard</h1><p className="mt-3 text-sm leading-6 text-text-secondary">{message ?? "Vui lòng kiểm tra kết nối rồi thử lại."}</p><Button onClick={onRetry} className="mt-6 rounded-full">Thử lại</Button></section></main>; }
function Field({ label, description, full, children }: { label: string; description: string; full?: boolean; children: React.ReactNode }) { return <label className={`block text-xs font-semibold text-text-secondary ${full ? "sm:col-span-2" : ""}`}><span className="text-foreground">{label}</span><span className="mt-1 block text-[11px] font-normal leading-4 text-text-muted">{description}</span><span className="mt-2 block">{children}</span></label>; }
function EmptyActivity() { return <div className="mt-5 rounded-[var(--radius-lg-token)] border border-dashed border-border bg-muted/50 p-7 text-center"><BookOpenCheck className="mx-auto text-primary" size={23} /><p className="mt-3 text-sm font-bold text-foreground">Bạn chưa có lượt làm bài được lưu</p><p className="mt-2 text-xs leading-5 text-text-secondary">Chọn một bộ đề để bắt đầu hành trình và xem tiến độ thực tế tại đây.</p><Button asChild variant="outline" className="mt-5 rounded-full"><Link href="/explore">Khám phá bộ đề <ArrowRight size={14} /></Link></Button></div>; }
