import { useAuth } from "@/_core/hooks/useAuth";
import SiteHeader from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, CircleDollarSign, Clock3, Crown, Loader2, LockKeyhole, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

const requestedPlanCode: Record<string, string> = { Pro: "pro_monthly", Premium: "premium_monthly" };
const formatVnd = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + "đ";

export default function TopUp() {
  const { user, loading } = useAuth();
  const [location] = useLocation();
  const summary = trpc.learner.summary.useQuery(undefined, { enabled: Boolean(user) });
  const offers = trpc.payment.offers.useQuery(undefined, { enabled: Boolean(user) });
  const createLink = trpc.payment.createLink.useMutation({
    onSuccess: result => window.location.assign(result.checkoutUrl),
    onError: error => toast.error(error.message || "Không thể tạo liên kết PayOS."),
  });
  const planParam = new URLSearchParams(location.split("?")[1] ?? "").get("plan");
  const selectedCode = planParam ? requestedPlanCode[planParam] : undefined;

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#eef4ff]"><CircleDollarSign className="animate-pulse text-[#2563eb]" /></div>;
  if (!user) return <div className="min-h-screen bg-[#eef4ff]"><SiteHeader /><main className="container grid min-h-[calc(100vh-76px)] place-items-center py-12"><section className="max-w-md rounded-[28px] bg-white p-8 text-center shadow-sm"><WalletCards className="mx-auto text-[#2563eb]" size={31} /><h1 className="mt-5 font-serif text-3xl font-semibold text-[#172554]">Nạp Point khi bạn sẵn sàng.</h1><p className="mt-3 text-sm leading-6 text-[#617786]">Đăng nhập để xem số dư hiện tại và chọn gói Point hoặc gói học phù hợp.</p><Button onClick={() => startLogin()} className="mt-7 rounded-full bg-[#2563eb]">Đăng nhập để tiếp tục</Button></section></main></div>;

  const selectedOffer = offers.data?.find(offer => offer.code === selectedCode);
  return <div className="min-h-screen bg-[#eef4ff]"><SiteHeader /><main className="container py-9 lg:py-12"><Link href="/vi" className="inline-flex items-center gap-2 text-xs font-bold text-[#617786]"><ArrowLeft size={15} /> Quay lại ví Point</Link><section className="mt-7 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-[30px] bg-[#172554] p-7 text-white sm:p-9"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#fbbf24]">Ví Point / Nạp & nâng cấp</p><h1 className="mt-4 max-w-xl font-serif text-[42px] font-semibold tracking-[-.05em]">Chọn nhịp học phù hợp tiếp theo.</h1><p className="mt-4 max-w-lg text-sm leading-6 text-[#eef4ff]">Thanh toán được tạo ở PayOS và Point hoặc quyền truy cập chỉ được cấp sau khi máy chủ xác minh webhook thành công.</p><div className="mt-8 grid grid-cols-2 gap-3"><Stat label="Point hiện có" value={String(summary.data?.profile.pointBalance ?? 0)} /><Stat label="Gói hiện tại" value={(summary.data?.profile.tier ?? "basic").toUpperCase()} /></div></div><aside className="rounded-[30px] border border-[#172554]/10 bg-white p-7"><LockKeyhole className="text-[#f59e0b]" size={25} /><p className="mt-6 text-[10px] font-bold uppercase tracking-[.16em] text-[#d97706]">Quy trình được bảo vệ</p><h2 className="mt-2 font-serif text-[29px] font-semibold text-[#172554]">Thanh toán qua PayOS</h2><p className="mt-3 text-sm leading-6 text-[#617786]">Mỗi đơn có mã riêng. Trang quay lại chỉ thông báo trạng thái; sổ cái Point và gói học chỉ đổi sau khi webhook đã đối soát số tiền, chữ ký và mã đơn.</p>{selectedOffer && <div className="mt-5 rounded-2xl bg-[#eef4ff] p-4"><p className="text-xs font-bold text-[#172554]">Lựa chọn từ bảng giá</p><p className="mt-1 text-sm text-[#617786]">{selectedOffer.label} · {formatVnd(selectedOffer.amount)}</p></div>}<Link href="/bang-gia" className="mt-5 inline-flex text-xs font-bold text-[#2563eb]">Xem điều khoản gói học</Link></aside></section>
    <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#2563eb]">Gói đã phê duyệt</p><h2 className="mt-2 font-serif text-3xl font-semibold text-[#172554]">Nạp Point hoặc mở khóa quyền học.</h2></div>{offers.isLoading && <Loader2 className="animate-spin text-[#2563eb]" />}</div>{offers.error && <p role="alert" className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-700">Không thể tải gói thanh toán: {offers.error.message}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{offers.data?.map(offer => <article key={offer.code} className={`rounded-[24px] border bg-white p-5 shadow-sm ${offer.code === selectedCode ? "border-[#2563eb] ring-2 ring-[#2563eb]/15" : "border-[#172554]/10"}`}><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-[#eef4ff] p-2 text-[#2563eb]">{offer.itemType === "membership" ? <Crown size={18} /> : <WalletCards size={18} />}</div>{offer.discounted && <span className="rounded-full bg-[#fef3c7] px-2 py-1 text-[10px] font-bold text-[#92400e]">Giảm 50% đầu tiên</span>}</div><h3 className="mt-5 text-lg font-bold text-[#172554]">{offer.label}</h3><p className="mt-2 text-2xl font-serif font-semibold text-[#172554]">{formatVnd(offer.amount)}<span className="ml-1 text-sm font-normal text-[#617786]">{offer.itemType === "membership" ? "/ tháng" : ""}</span></p>{offer.discounted && <p className="mt-1 text-xs text-[#617786] line-through">Giá gốc {formatVnd(offer.regularAmount)}</p>}<ul className="mt-5 space-y-2 text-xs leading-5 text-[#617786]"><li className="flex gap-2"><Check size={14} className="mt-0.5 shrink-0 text-[#2563eb]" />{offer.itemType === "membership" ? `Tặng ${offer.pointAmount} Point khi kích hoạt` : `Cộng ${offer.pointAmount} Point sau xác minh`}</li><li className="flex gap-2"><Check size={14} className="mt-0.5 shrink-0 text-[#2563eb]" />Ghi sổ cái minh bạch</li></ul><Button onClick={() => createLink.mutate({ packageCode: offer.code })} disabled={createLink.isPending} className="mt-6 w-full rounded-full bg-[#2563eb]">{createLink.isPending ? <><Loader2 className="animate-spin" /> Đang tạo đơn...</> : "Thanh toán PayOS"}</Button></article>)}</div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><InfoCard icon={ShieldCheck} title="Ghi nhận an toàn" body="Point chỉ được cộng sau khi giao dịch được máy chủ xác thực." /><InfoCard icon={Clock3} title="Trạng thái minh bạch" body="Mọi biến động xuất hiện trong sổ cái ví Point." /><InfoCard icon={CircleDollarSign} title="Quyền truy cập rõ ràng" body="Nâng cấp gói được đối soát trước khi mở nội dung trả phí." /></section></main></div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-4"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#bfdbfe]">{label}</p><p className="mt-2 font-serif text-3xl font-semibold">{value}</p></div>; }
function InfoCard({ icon: Icon, title, body }: { icon: typeof ShieldCheck; title: string; body: string }) { return <article className="rounded-[22px] border border-[#172554]/10 bg-white p-5"><Icon className="text-[#2563eb]" size={19} /><h2 className="mt-4 text-sm font-bold text-[#172554]">{title}</h2><p className="mt-2 text-xs leading-5 text-[#617786]">{body}</p></article>; }
