import { useAuth } from "@/_core/hooks/useAuth";
import { CreditCard, GraduationCap, HandHeart, History, LayoutDashboard, LogOut, Medal, PlusCircle, Sparkles, Target, Trophy, UserRound, UsersRound } from "lucide-react";
import { useLocation } from "wouter";
import { ROUTES } from "@/lib/routes";

const links = [
  [LayoutDashboard, "Bảng điều khiển", ROUTES.account], [Target, "Nhiệm vụ", ROUTES.missions], [Medal, "Thành tích", ROUTES.achievements], [PlusCircle, "Quiz của tôi", ROUTES.myQuizzes], [GraduationCap, "Làm Quiz", ROUTES.explore], [Trophy, "Bảng xếp hạng", ROUTES.leaderboard], [UsersRound, "Mời bạn bè", ROUTES.referrals], [UserRound, "Thông tin cá nhân", `${ROUTES.account}#thiet-lap`], [CreditCard, "Nạp Point", ROUTES.billing], [Sparkles, "Nâng cấp tài khoản", ROUTES.pricing], [History, "Lịch sử giao dịch", ROUTES.wallet], [HandHeart, "Hỗ trợ", "mailto:support@dshare.vn"],
] as const;

export default function AccountSidebar() {
  const { user, logout } = useAuth(); const [location, setLocation] = useLocation();
  return <aside className="sticky top-[76px] hidden h-[calc(100dvh-76px)] w-64 shrink-0 self-start overflow-hidden border-r border-border bg-surface/90 p-4 backdrop-blur lg:flex lg:flex-col"><div className="shrink-0 rounded-[var(--radius-lg-token)] bg-primary-light p-4"><div className="grid h-11 w-11 place-items-center rounded-[var(--radius-md-token)] bg-primary font-serif text-lg font-bold text-primary-foreground">{user?.name?.slice(0, 1).toUpperCase() ?? "D"}</div><p className="mt-3 truncate text-sm font-bold text-foreground">{user?.name ?? "Tài khoản Dshare"}</p><p className="mt-1 text-[11px] text-muted-foreground">Không gian học tập cá nhân</p></div><nav className="mt-5 min-h-0 flex-1 space-y-1 overflow-y-auto overscroll-contain pr-1" aria-label="Điều hướng tài khoản">{links.map(([Icon, label, href]) => { const active = location === href.split("#")[0]; return <button key={label} type="button" onClick={() => href.startsWith("mailto:") ? window.location.assign(href) : setLocation(href)} className={`flex min-h-11 w-full items-center gap-3 rounded-[var(--radius-md-token)] px-3 text-left text-xs font-semibold transition-colors ${active ? "bg-primary-light text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`} aria-current={active ? "page" : undefined}><Icon size={16} />{label}</button>; })}</nav><button type="button" onClick={logout} className="mt-4 flex min-h-11 w-full shrink-0 items-center gap-3 rounded-[var(--radius-md-token)] border border-border px-3 text-left text-xs font-bold text-destructive hover:bg-destructive/8"><LogOut size={16} />Đăng xuất</button></aside>;
}
