import { CPanelPageHeader } from "@/components/CPanelPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { ROUTES } from "@/lib/routes";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, KeyRound, Loader2, PlugZap, Save, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function AdminAiAssistantPanel() {
  const config = trpc.aiAssistantAdmin.config.useQuery(); const manusModels = trpc.aiAssistantAdmin.manusModels.useQuery(undefined, { enabled: config.data?.provider === "manus" }); const memberships = trpc.admin.membershipManagement.useQuery(); const [, setLocation] = useLocation();
  const [provider, setProvider] = useState<"manus" | "gemini">("manus"); const [model, setModel] = useState("gpt-5-mini"); const [apiKey, setApiKey] = useState(""); const [isEnabled, setIsEnabled] = useState(false); const [welcomeMessage, setWelcomeMessage] = useState("");
  const save = trpc.aiAssistantAdmin.saveConfig.useMutation({ onSuccess: () => { setApiKey(""); config.refetch(); toast.success("Đã lưu cấu hình AI Assistant.", { description: "API key được mã hóa; Gemini tự chọn model hỗ trợ chat." }); }, onError: error => toast.error("Không thể lưu cấu hình AI", { description: error.message }) });
  const testConnection = trpc.aiAssistantAdmin.testGeminiConnection.useMutation({ onSuccess: result => toast.success("Kết nối Gemini thành công.", { description: `Model được tự chọn: ${result.model}` }), onError: error => toast.error("Không thể kết nối Gemini", { description: error.message }) });
  useEffect(() => { if (config.data) { setProvider(config.data.provider); setModel(config.data.model); setIsEnabled(config.data.isEnabled); setWelcomeMessage(config.data.welcomeMessage); } }, [config.data]);
  const hasGeminiKey = provider === "gemini" && config.data?.provider === "gemini" && config.data.hasApiKey; const activeGeminiModel = config.data?.provider === "gemini" ? config.data.model : null; const allowed = memberships.data?.groups.filter(group => group.permissions.some(permission => permission.permissionKey === "canUseAi" && permission.isAllowed)) ?? []; const blocked = memberships.data?.groups.filter(group => !group.permissions.some(permission => permission.permissionKey === "canUseAi" && permission.isAllowed)) ?? []; const canSave = welcomeMessage.trim() && (provider === "gemini" ? Boolean(apiKey.trim() || hasGeminiKey) : Boolean(model.trim())); const submit = () => save.mutate({ provider, model: provider === "manus" ? model : undefined, apiKey: apiKey || undefined, isEnabled, welcomeMessage });
  return <div className="mx-auto max-w-[1440px]"><CPanelPageHeader eyebrow="System / AI Content & Learning Copilot" title="AI Assistant" description="Cấu hình copilot tạo nội dung, giải thích đáp án và hỗ trợ học tập với quyền và quota theo gói." actions={<Button onClick={submit} disabled={save.isPending || !canSave} className="rounded-[var(--radius-md-token)]">{save.isPending ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}Lưu cấu hình</Button>} />
    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_380px]"><section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Bot size={20} /></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Provider configuration</p><h2 className="mt-1 text-2xl font-bold text-foreground">Kết nối mô hình</h2></div></div><div className="mt-6 space-y-5"><div><Label>Nhà cung cấp</Label><div className="mt-2 grid grid-cols-2 gap-3"><ProviderCard active={provider === "manus"} title="Manus AI" description="Dùng khóa quản lý an toàn của hệ thống Manus." onClick={() => setProvider("manus")} /><ProviderCard active={provider === "gemini"} title="Google Gemini" description="Chỉ cần Gemini API key; model tự động được chọn." onClick={() => setProvider("gemini")} /></div></div>{provider === "manus" ? <div><Label htmlFor="ai-model">Mã mô hình Manus</Label><Input id="ai-model" list="manus-models" value={model} onChange={event => setModel(event.target.value)} className="mt-2" placeholder="gpt-5-mini" /><datalist id="manus-models">{manusModels.data?.map(item => <option key={item} value={item} />)}</datalist></div> : <GeminiControls apiKey={apiKey} setApiKey={setApiKey} hasGeminiKey={hasGeminiKey} activeModel={activeGeminiModel} testConnection={testConnection} />}<div><Label htmlFor="assistant-welcome">Lời chào mặc định</Label><Textarea id="assistant-welcome" value={welcomeMessage} onChange={event => setWelcomeMessage(event.target.value)} className="mt-2 min-h-28" maxLength={500} /></div></div></section>
      <aside className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><Sparkles className="text-primary" size={22} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-primary">Service status</p><h2 className="mt-2 text-2xl font-bold text-foreground">AI Assistant {isEnabled ? "đang bật" : "đang tạm dừng"}</h2><p className="mt-3 text-sm leading-6 text-text-secondary">Khi được bật, nhóm có quyền AI có thể dùng copilot theo quota gói thành viên.</p><div className="mt-6 flex items-center justify-between rounded-[var(--radius-md-token)] bg-muted p-4"><div><p className="text-xs font-bold text-foreground">Cho phép người dùng sử dụng</p><p className="mt-1 text-[10px] text-text-secondary">Áp dụng quota AI của gói thành viên.</p></div><Switch checked={isEnabled} onCheckedChange={setIsEnabled} aria-label="Bật AI Assistant" /></div><div className="mt-5 rounded-[var(--radius-md-token)] border border-success/20 bg-success/5 p-4"><ShieldCheck size={18} className="text-success" /><p className="mt-3 text-xs font-bold text-foreground">Bảo vệ API key</p><p className="mt-1 text-[10px] leading-5 text-text-secondary">API key không được trả về từ máy chủ hay hiển thị trong nhật ký.</p></div><div className="mt-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-text-muted">Copilot capabilities</p><div className="mt-3 space-y-2">{["Generate Questions", "Generate Quiz", "Improve Question", "Explain Answer", "Analyze Quiz", "Detect Duplicate"].map(item => <div key={item} className="flex items-center gap-2 text-xs text-text-secondary"><CheckCircle2 size={14} className="text-primary" />{item}</div>)}</div></div></aside></section>
    <section className="mt-6 rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Permission-aware access</p><h2 className="mt-2 text-2xl font-bold text-foreground">Quyền dùng AI theo nhóm</h2><p className="mt-2 text-sm text-text-secondary">Máy chủ chỉ cho chat khi nhóm thành viên bật <strong>canUseAi</strong>; quota AI được áp dụng riêng.</p></div><Button type="button" variant="outline" onClick={() => setLocation(ROUTES.adminUserGroups)} className="rounded-[var(--radius-md-token)]">Quản lý quyền</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><GroupPermissionCard tone="success" label={`Được phép · ${allowed.length}`} groups={allowed.map(group => group.name)} empty="Chưa có nhóm nào." /><GroupPermissionCard tone="danger" label={`Chưa cấp quyền · ${blocked.length}`} groups={blocked.map(group => group.name)} empty="Tất cả nhóm đều được cấp quyền." /></div></section></div>;
}
function ProviderCard({ active, title, description, onClick }: { active: boolean; title: string; description: string; onClick: () => void }) { return <button type="button" onClick={onClick} className={`rounded-[var(--radius-md-token)] border p-4 text-left transition-colors ${active ? "border-primary bg-primary-light" : "border-border bg-surface hover:bg-muted"}`}><p className="text-sm font-bold text-foreground">{title}</p><p className="mt-1 text-[11px] leading-5 text-text-secondary">{description}</p></button>; }
function GeminiControls({ apiKey, setApiKey, hasGeminiKey, activeModel, testConnection }: { apiKey: string; setApiKey: (value: string) => void; hasGeminiKey: boolean; activeModel: string | null; testConnection: any }) { return <><div className="rounded-[var(--radius-md-token)] border border-success/20 bg-success/5 p-4"><p className="text-xs font-bold text-success">Model Gemini tự động</p><p className="mt-1 text-[11px] leading-5 text-text-secondary">Máy chủ kiểm tra API key, đọc model có quyền generateContent và tự chọn Flash phù hợp cho chat.</p>{activeModel ? <p className="mt-2 text-xs font-semibold text-foreground">Đang dùng: {activeModel}</p> : null}</div><div><Label htmlFor="gemini-key">Gemini API key</Label><div className="relative mt-2"><KeyRound size={16} className="absolute left-3 top-3 text-text-muted" /><Input id="gemini-key" type="password" value={apiKey} onChange={event => setApiKey(event.target.value)} className="pl-9" placeholder={hasGeminiKey ? "Đã lưu khóa mã hóa — nhập để thay thế" : "Dán Gemini API key"} autoComplete="new-password" /></div><div className="mt-2 flex flex-wrap items-center gap-2"><Button type="button" variant="outline" onClick={() => testConnection.mutate({ apiKey: apiKey.trim() })} disabled={!apiKey.trim() || testConnection.isPending} className="h-9 rounded-[var(--radius-sm-token)] text-xs text-success hover:text-success">{testConnection.isPending ? <Loader2 className="animate-spin" size={14} /> : <PlugZap size={14} />}Kiểm tra kết nối</Button><p className="text-[10px] text-text-muted">Khóa không lưu khi bạn chưa bấm Lưu cấu hình.</p></div></div></>; }
function GroupPermissionCard({ tone, label, groups, empty }: { tone: "success" | "danger"; label: string; groups: string[]; empty: string }) { return <div className={`rounded-[var(--radius-md-token)] p-4 ${tone === "success" ? "bg-success/5" : "bg-danger/5"}`}><p className={`text-[10px] font-bold uppercase tracking-[.12em] ${tone === "success" ? "text-success" : "text-danger"}`}>{label}</p><p className="mt-2 text-sm text-foreground">{groups.length ? groups.join(" · ") : empty}</p></div>; }
