import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowRight, BarChart3, BookOpenCheck, CircleDollarSign, ClipboardList, FileWarning, FolderTree, Loader2, Plus, ScrollText, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";

const quickActions = [
  ["Quản lý Chủ đề", "/quan-tri/chu-de", FolderTree],
  ["Quiz System", "/quan-tri/quiz-system", BookOpenCheck],
  ["Tạo Quiz", "/quan-tri/quiz-system", Plus],
  ["Activity Logs", "/quan-tri/nhat-ky", ScrollText],
  ["Người dùng", "/quan-tri/nguoi-dung", UsersRound],
  ["Xem báo cáo", "/quan-tri/bao-cao", BarChart3],
] as const;

export default function AdminOperationsDashboard() {
  const overview = trpc.admin.overview.useQuery();
  const analytics = trpc.admin.analytics.useQuery();
  const reports = trpc.admin.reports.useQuery();
  const audit = trpc.admin.auditTrail.useQuery({ action: undefined });
  const pending = reports.data?.filter(item => item.report.status === "pending") ?? [];
  const error = overview.error || analytics.error || reports.error || audit.error;
  const loading = overview.isLoading || analytics.isLoading || reports.isLoading || audit.isLoading;
  const refresh = () => { overview.refetch(); analytics.refetch(); reports.refetch(); audit.refetch(); };
  const learningSignals = [
    { label: "Tỷ lệ đạt", value: `${analytics.data?.passRate ?? 0}%`, note: "Theo bài đã nộp", progress: analytics.data?.passRate ?? 0 },
    { label: "Lượt làm Quiz", value: `${overview.data?.submitted ?? 0}`, note: "Lượt hoàn thành", progress: Math.min(100, (overview.data?.submitted ?? 0) * 10) },
    { label: "Người học", value: `${overview.data?.users ?? 0}`, note: "Tài khoản học tập", progress: Math.min(100, (overview.data?.users ?? 0) * 10) },
  ];
  const kpis = [
    { label: "Người học", value: overview.data?.users ?? 0, note: "Tổng tài khoản học tập", icon: UsersRound, href: "/quan-tri/nguoi-dung" },
    { label: "Lượt làm Quiz", value: overview.data?.submitted ?? 0, note: "Bài đã nộp", icon: ClipboardList, href: "/quan-tri/bao-cao" },
    { label: "Point đã tiêu", value: analytics.data?.pointsConsumed ?? 0, note: "Dòng Point đã ghi nhận", icon: CircleDollarSign, href: "/quan-tri/point" },
    { label: "Cần kiểm duyệt", value: pending.length, note: "Báo lỗi đang chờ xử lý", icon: FileWarning, href: "/quan-tri/bao-loi" },
  ];

  return <div className="mx-auto max-w-[1440px]">
    <header className="flex flex-col gap-6 border-b border-border pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-primary">Dshare / Learning Control Center</p><h1 className="mt-2 text-[clamp(2rem,4vw,2.6rem)] font-bold tracking-[-.05em] text-foreground">Điều hành học tập, không chỉ vận hành dữ liệu.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-text-secondary">Theo dõi tín hiệu học tập, Point economy và công việc cần xử lý từ một không gian quản trị thống nhất.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-[var(--radius-md-token)]"><Link href="/quan-tri/nhat-ky"><ScrollText size={15} />Nhật ký hoạt động</Link></Button><Button asChild className="rounded-[var(--radius-md-token)]"><Link href="/quan-tri/quiz-system"><Plus size={16} />Tạo Quiz</Link></Button></div></header>

    {error ? <section className="mt-6 rounded-[var(--radius-lg-token)] border border-danger/25 bg-danger/5 p-5 text-sm text-danger" role="alert"><strong>Chưa tải được một phần dữ liệu điều hành.</strong><p className="mt-1">{error.message}</p><Button onClick={refresh} className="mt-4 rounded-[var(--radius-md-token)]">Thử lại</Button></section> : <>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({ label, value, note, icon: Icon, href }) => <Link key={label} href={href} className="group rounded-[var(--radius-lg-token)] border border-border bg-surface p-5 transition-[border-color,box-shadow,transform] duration-200 hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-[var(--shadow-sm)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/20"><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Icon size={18} /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-text-muted">{label}</p><p className="mt-1 text-3xl font-bold tracking-[-.04em] text-foreground">{loading ? "—" : value}</p><p className="mt-1 text-[11px] text-text-secondary">{note}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-primary">Xem chi tiết <ArrowRight size={13} className="transition-transform group-hover:translate-x-0.5" /></span></Link>)}</section>

      <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Learning intelligence</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em] text-foreground">Tín hiệu học tập trọng yếu</h2><p className="mt-2 text-sm text-text-secondary">Ưu tiên insight giúp điều chỉnh nội dung và trải nghiệm học tập.</p></div><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Activity size={19} /></span></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{learningSignals.map(signal => <div key={signal.label} className="rounded-[var(--radius-md-token)] bg-muted p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-text-muted">{signal.label}</p><p className="mt-2 text-2xl font-bold text-foreground">{loading ? "—" : signal.value}</p><p className="mt-1 text-[11px] text-text-secondary">{signal.note}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-primary transition-[width] duration-200" style={{ width: `${signal.progress}%` }} /></div></div>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-[var(--radius-md-token)] border border-border bg-background px-4 py-3"><p className="text-xs leading-5 text-text-secondary">Phân tích sâu về kết quả, mức độ khó và hiệu quả nội dung nằm trong khu Analytics.</p><Button asChild variant="outline" size="sm" className="rounded-[var(--radius-sm-token)]"><Link href="/quan-tri/bao-cao">Mở Analytics <ArrowRight size={14} /></Link></Button></div></section>
        <section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Moderation center</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em] text-foreground">Hàng đợi cần xử lý</h2></div><span className="rounded-full bg-warning/10 px-3 py-1.5 text-xs font-bold text-warning">{pending.length} chờ duyệt</span></div>{reports.isLoading ? <div className="grid min-h-44 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : pending.length ? <div className="mt-5 space-y-3">{pending.slice(0, 3).map(item => <div key={item.report.id} className="rounded-[var(--radius-md-token)] bg-muted p-4"><p className="text-xs font-bold text-foreground">Câu hỏi #{item.report.questionId} · {item.reporter ?? "Học viên"}</p><p className="mt-2 line-clamp-2 text-[11px] leading-5 text-text-secondary">{item.report.details}</p></div>)}</div> : <div className="mt-5 rounded-[var(--radius-md-token)] bg-muted p-5 text-sm leading-6 text-text-secondary"><AlertTriangle className="mb-2 text-primary" size={18} />Không có báo lỗi nào đang chờ kiểm duyệt.</div>}<Button asChild variant="outline" className="mt-5 rounded-[var(--radius-md-token)]"><Link href="/quan-tri/bao-loi">Xem tất cả <ArrowRight size={14} /></Link></Button></section></section>

      <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.7fr)]"><section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Gamification overview</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em] text-foreground">Point economy, tách biệt với XP</h2><p className="mt-2 text-sm text-text-secondary">Point phản ánh economy; XP là progression học tập và sẽ được kích hoạt ở phase domain riêng.</p></div><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><CircleDollarSign size={19} /></span></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><EconomyMetric label="Point nạp" value={analytics.data?.pointsTopUp ?? 0} note="Top up đã ghi nhận" /><EconomyMetric label="Point đã tiêu" value={analytics.data?.pointsConsumed ?? 0} note="Phí tham gia" /><EconomyMetric label="Point đã thưởng" value={analytics.data?.pointsRewarded ?? 0} note="Thưởng & bồi hoàn" /></div><div className="mt-6 flex items-center gap-3 rounded-[var(--radius-md-token)] border border-info/15 bg-info/5 px-4 py-3 text-xs leading-5 text-info"><Sparkles size={16} className="shrink-0" />Hệ XP, nhiệm vụ, streak và achievement chưa được khởi tạo dữ liệu; dashboard không hiển thị số liệu thay thế.</div></section>
        <section className="rounded-[var(--radius-xl-token)] border border-border bg-muted p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Quick actions</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em] text-foreground">Bắt đầu đúng tác vụ.</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{quickActions.map(([label, href, Icon]) => <Link key={label} href={href} className="flex min-h-11 items-center gap-3 rounded-[var(--radius-md-token)] border border-border bg-surface px-3 text-xs font-semibold text-foreground transition-colors hover:border-primary/30 hover:text-primary focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/20"><Icon size={16} className="text-primary" />{label}</Link>)}</div></section></section>

      <section className="mt-6 rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Recent activity</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em] text-foreground">Hoạt động gần đây</h2></div><Button asChild variant="outline" size="sm" className="rounded-[var(--radius-sm-token)]"><Link href="/quan-tri/nhat-ky">Mở Activity Logs <ArrowRight size={14} /></Link></Button></div>{audit.isLoading ? <div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : audit.data?.length ? <div className="mt-5 divide-y divide-border-light">{audit.data.slice(0, 5).map(item => <div key={item.log.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="text-sm font-semibold text-foreground">{item.actorName ?? item.actorEmail ?? "Hệ thống"}</p><p className="mt-1 text-xs text-text-secondary"><span className="font-mono text-primary">{item.log.action}</span> · {item.log.entityType}{item.log.entityId ? ` #${item.log.entityId}` : ""}</p></div><time className="shrink-0 text-xs text-text-muted">{item.log.createdAt.toLocaleString("vi-VN")}</time></div>)}</div> : <div className="mt-5 rounded-[var(--radius-md-token)] bg-muted p-5 text-sm text-text-secondary">Chưa có hoạt động quản trị nào để hiển thị.</div>}</section>
    </>}
  </div>;
}

function EconomyMetric({ label, value, note }: { label: string; value: number; note: string }) {
  return <div className="rounded-[var(--radius-md-token)] bg-muted p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-foreground">{value}</p><p className="mt-1 text-[11px] text-text-secondary">{note}</p></div>;
}
