import { CPanelPageHeader } from "@/components/CPanelPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getWalletTransactionMeta, type WalletTransactionKind } from "@/lib/walletUtils";
import { trpc } from "@/lib/trpc";
import { ROUTES } from "@/lib/routes";
import { CircleDollarSign, Info, Loader2, RefreshCw, Search } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const ledgerTypes: Array<{ value: "all" | WalletTransactionKind; label: string }> = [{ value: "all", label: "Mọi giao dịch" }, { value: "top_up", label: "Nạp Point" }, { value: "quiz_fee", label: "Phí làm bài" }, { value: "quiz_reward", label: "Thưởng hoàn thành" }, { value: "report_reward", label: "Bồi hoàn báo lỗi" }, { value: "referral_reward", label: "Thưởng giới thiệu" }, { value: "admin_adjustment", label: "Điều chỉnh quản trị" }];

export default function AdminPointLedgerPanel() {
  const [search, setSearch] = useState(""); const [type, setType] = useState<"all" | WalletTransactionKind>("all"); const query = trpc.admin.pointLedger.useQuery({ search: search || undefined, type: type === "all" ? undefined : type });
  return <div className="mx-auto max-w-[1440px]"><CPanelPageHeader eyebrow="Gamification / Point economy" title="Sổ cái Point" description="Theo dõi biến động Point, số dư sau giao dịch và nguồn phát sinh để điều hành economy minh bạch." actions={<Button asChild className="rounded-[var(--radius-md-token)]"><Link href={ROUTES.adminUsers}>Điều chỉnh Point học viên</Link></Button>} />
    <section className="mt-6 rounded-[var(--radius-lg-token)] border border-border bg-surface p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_240px_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={16} /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm tên hoặc email học viên…" className="pl-9" aria-label="Tìm sổ cái Point" /></label><select value={type} onChange={event => setType(event.target.value as typeof type)} aria-label="Lọc loại giao dịch Point" className="h-10 rounded-[var(--radius-sm-token)] border border-input bg-surface px-3 text-sm text-foreground">{ledgerTypes.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select><Button onClick={() => query.refetch()} variant="outline" className="rounded-[var(--radius-md-token)]"><RefreshCw size={15} className={query.isFetching ? "animate-spin" : ""} />Làm mới</Button></div></section>
    {query.isLoading ? <div className="grid min-h-64 place-items-center text-sm text-text-secondary"><span className="flex items-center gap-2"><Loader2 className="animate-spin text-primary" size={17} />Đang tải sổ cái Point…</span></div> : query.error ? <div className="mt-6 rounded-[var(--radius-lg-token)] border border-danger/25 bg-danger/5 p-6 text-sm text-danger"><strong>Chưa tải được sổ cái Point.</strong><p className="mt-1">{query.error.message}</p><Button onClick={() => query.refetch()} className="mt-4 rounded-[var(--radius-md-token)]">Thử lại</Button></div> : <><section className="mt-6 overflow-hidden rounded-[var(--radius-xl-token)] border border-border bg-surface"><div className="flex items-center gap-3 border-b border-border px-5 py-5"><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><CircleDollarSign size={19} /></span><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">Point transactions</p><h2 className="mt-1 text-xl font-bold text-foreground">{query.data?.length ?? 0} giao dịch gần nhất</h2></div></div>{query.data?.length ? <div className="divide-y divide-border-light">{query.data.map(row => { const meta = getWalletTransactionMeta(row.transaction.type as WalletTransactionKind, row.transaction.amount); return <div key={row.transaction.id} className="flex flex-col gap-3 px-5 py-4 lg:grid lg:grid-cols-[48px_minmax(0,1fr)_220px_180px] lg:items-center"><span className={`grid size-10 place-items-center rounded-[var(--radius-md-token)] ${meta.credit ? "bg-success/10 text-success" : "bg-muted text-text-secondary"}`}><CircleDollarSign size={17} /></span><div className="min-w-0"><p className="text-sm font-bold text-foreground">{meta.label}</p><p className="mt-1 text-[11px] text-text-secondary">{row.transaction.description}</p></div><div className="min-w-0"><p className="text-xs font-semibold text-foreground">{row.userName ?? "Học viên"}</p><p className="mt-1 truncate text-[10px] text-text-muted">{row.userEmail ?? `ID #${row.transaction.userId}`}</p></div><div className="lg:text-right"><p className={`text-lg font-bold ${meta.credit ? "text-success" : "text-foreground"}`}>{meta.credit ? "+" : ""}{row.transaction.amount} Point</p><p className="mt-1 text-[10px] text-text-muted">Số dư {row.transaction.balanceAfter} · {row.transaction.createdAt.toLocaleString("vi-VN")}</p></div></div>; })}</div> : <EmptyLedger />}</section><section className="mt-6 rounded-[var(--radius-lg-token)] border border-info/15 bg-info/5 p-5 text-xs leading-6 text-info"><Info className="mb-2" size={16} /><strong>Point là currency/economy.</strong> XP là hệ progression học tập riêng và không được suy diễn từ số dư hoặc giao dịch Point trong sổ cái này.</section></>}</div>;
}
function EmptyLedger() { return <div className="grid min-h-56 place-items-center px-6 text-center"><div><CircleDollarSign className="mx-auto text-primary" size={28} /><h2 className="mt-4 text-2xl font-bold text-foreground">Chưa có giao dịch phù hợp</h2><p className="mt-2 max-w-md text-sm leading-6 text-text-secondary">Khi phát sinh phí làm bài, thưởng, bồi hoàn hoặc điều chỉnh Point, các giao dịch sẽ xuất hiện ở đây.</p></div></div>; }
