import { CPanelPageHeader } from "@/components/CPanelPageHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, CircleDollarSign, ClipboardList, Info, Loader2, UsersRound } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";

export default function AnalyticsControlPanel() {
  const analytics = trpc.admin.analytics.useQuery();
  const data = analytics.data;
  const pointEconomy = [{ label: "Nạp", value: data?.pointsTopUp ?? 0, fill: "var(--primary)" }, { label: "Tiêu", value: data?.pointsConsumed ?? 0, fill: "var(--warning)" }, { label: "Thưởng", value: data?.pointsRewarded ?? 0, fill: "var(--success)" }];
  const kpis = [{ label: "Người học", value: data?.users ?? 0, suffix: "", icon: UsersRound }, { label: "Lượt hoàn thành", value: data?.completed ?? 0, suffix: "", icon: ClipboardList }, { label: "Tỷ lệ đạt", value: data?.passRate ?? 0, suffix: "%", icon: BarChart3 }, { label: "Point đã tiêu", value: data?.pointsConsumed ?? 0, suffix: "", icon: CircleDollarSign }];
  if (analytics.isLoading) return <div className="mx-auto grid min-h-64 max-w-[1440px] place-items-center" role="status"><span className="flex items-center gap-2 text-sm text-text-secondary"><Loader2 className="animate-spin text-primary" />Đang tổng hợp dữ liệu Analytics…</span></div>;
  if (analytics.error) return <div className="mx-auto max-w-[1440px] rounded-[var(--radius-lg-token)] border border-danger/25 bg-danger/5 p-6 text-sm text-danger" role="alert"><strong>Chưa tải được Analytics.</strong><p className="mt-1">{analytics.error.message}</p><Button onClick={() => analytics.refetch()} className="mt-4 rounded-[var(--radius-md-token)]">Thử lại</Button></div>;
  return <div className="mx-auto max-w-[1440px]"><CPanelPageHeader eyebrow="Analytics / Learning intelligence" title="Analytics" description="Đọc tín hiệu học tập và Point economy để ưu tiên nội dung, không chỉ hiển thị biểu đồ." actions={<Button asChild variant="outline" className="rounded-[var(--radius-md-token)]"><Link href="/quan-tri/point">Mở sổ cái Point <ArrowRight size={15} /></Link></Button>} />
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({ label, value, suffix, icon: Icon }) => <div key={label} className="rounded-[var(--radius-lg-token)] border border-border bg-surface p-5"><Icon size={18} className="text-primary" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.13em] text-text-muted">{label}</p><p className="mt-1 text-3xl font-bold text-foreground">{value}{suffix}</p></div>)}</section>
    <section className="mt-6 grid gap-5 xl:grid-cols-2"><ChartCard eyebrow="Point analytics" title="Dòng Point thực tế"><ResponsiveContainer><BarChart data={pointEconomy}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fill: "var(--text-secondary)", fontSize: 12 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "var(--text-secondary)", fontSize: 12 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "var(--muted)" }} contentStyle={{ borderColor: "var(--border)", borderRadius: "10px", backgroundColor: "var(--surface)", color: "var(--text)" }} /><Bar dataKey="value" radius={[6, 6, 0, 0]}>{pointEconomy.map(item => <Cell key={item.label} fill={item.fill} />)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard eyebrow="Quiz analytics" title="Lượt làm theo bộ đề"><ResponsiveContainer><BarChart data={data?.popularQuizzes ?? []}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="title" hide /><YAxis tick={{ fill: "var(--text-secondary)", fontSize: 12 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "var(--muted)" }} contentStyle={{ borderColor: "var(--border)", borderRadius: "10px", backgroundColor: "var(--surface)", color: "var(--text)" }} /><Bar dataKey="count" name="Lượt làm" fill="var(--primary)" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Content performance</p><h2 className="mt-2 text-2xl font-bold text-foreground">Bộ đề có lượt làm cao</h2>{data?.popularQuizzes.length ? <div className="mt-5 divide-y divide-border-light">{data.popularQuizzes.map((quiz, index) => <div key={quiz.title} className="flex items-center gap-4 py-4"><span className="grid size-8 place-items-center rounded-full bg-primary-light text-xs font-bold text-primary">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-foreground">{quiz.title}</p><p className="mt-1 text-xs text-text-secondary">{quiz.count} lượt làm · {quiz.passRate}% đạt</p></div></div>)}</div> : <div className="mt-5 rounded-[var(--radius-md-token)] bg-muted p-5 text-sm text-text-secondary">Chưa có lượt làm để phân tích hiệu suất nội dung.</div>}</div><aside className="rounded-[var(--radius-xl-token)] border border-info/15 bg-info/5 p-6"><Info className="text-info" size={20} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.15em] text-info">Architecture note</p><h2 className="mt-2 text-xl font-bold text-foreground">Point không phải XP</h2><p className="mt-3 text-sm leading-6 text-text-secondary">Analytics hiện tổng hợp Point economy bằng dữ liệu sổ cái. XP, retention, cohort, streak và mission sẽ được bổ sung khi domain dữ liệu riêng được khởi tạo.</p></aside></section></div>;
}

function ChartCard({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-foreground">{title}</h2><div className="mt-5 h-64">{children}</div></section>; }
