import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const defaults = { primary: "#065BE5", accent: "#3762D2", success: "#007453", attention: "#DE1264", page: "#EBF4FF", surface: "#FFFFFF" };
const studioWidthDefaults = { questions: 1440, settings: 1040 };
type BrandKey = keyof typeof defaults;
type BrandColors = Record<BrandKey, string>;
type StudioWidths = typeof studioWidthDefaults;

export default function BrandSettingsPanel() {
  const query = trpc.branding.get.useQuery();
  const saveMutation = trpc.branding.save.useMutation({ onSuccess: () => { query.refetch(); toast.success("Đã đồng bộ nhận diện trên mọi thiết bị."); } });
  const [colors, setColors] = useState<BrandColors>(defaults);
  const [studioWidths, setStudioWidths] = useState<StudioWidths>(studioWidthDefaults);
  useEffect(() => { if (query.data) { setColors({ primary: query.data.primaryColor, accent: query.data.accentColor, success: query.data.successColor, attention: query.data.attentionColor, page: query.data.pageColor, surface: query.data.surfaceColor }); setStudioWidths({ questions: query.data.questionTabContentWidth ?? studioWidthDefaults.questions, settings: query.data.settingsTabContentWidth ?? studioWidthDefaults.settings }); } }, [query.data]);
  const save = () => saveMutation.mutate({ primaryColor: colors.primary, accentColor: colors.accent, successColor: colors.success, attentionColor: colors.attention, pageColor: colors.page, surfaceColor: colors.surface, questionTabContentWidth: studioWidths.questions, settingsTabContentWidth: studioWidths.settings });
  const reset = () => { setColors(defaults); setStudioWidths(studioWidthDefaults); };
  return <section className="mx-auto max-w-6xl rounded-[28px] border border-[#172554]/10 bg-white p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#3762d2]">Thiết lập nhận diện</p><h1 className="mt-2 font-serif text-3xl font-semibold text-[#141432]">Tùy chỉnh Style trang web</h1><p className="mt-2 text-sm text-[#6c6c7a]">Cấu hình được lưu dùng chung cho toàn bộ trang web.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{(Object.keys(colors) as BrandKey[]).map(key => <label key={key} className="rounded-2xl bg-[#f0f1ff] p-4 text-xs font-bold text-[#141432]"><span className="capitalize">{key}</span><div className="mt-3 flex gap-2"><span className="h-10 w-10 rounded-xl border border-black/10" style={{ backgroundColor: colors[key] }} /><Input value={colors[key]} onChange={event => setColors(current => ({ ...current, [key]: event.target.value }))} aria-label={`Màu ${key}`} /></div></label>)}</div><section className="mt-6 rounded-2xl border border-[#172554]/10 bg-[#f8faff] p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#3762d2]">Studio Tạo Quiz</p><h2 className="mt-1 text-base font-bold text-[#141432]">Kích thước vùng nội dung</h2><p className="mt-1 text-xs leading-5 text-[#6c6c7a]">Điều chỉnh chiều rộng tối đa trên màn hình lớn; trên điện thoại, nội dung luôn tự co vừa màn hình.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{([['questions', 'Tab Câu hỏi', 'Khối tạo nhanh, trình soạn và Live Preview'], ['settings', 'Tab Cài đặt', 'Thông tin Quiz, ảnh bìa và cấu hình làm bài']] as const).map(([key, label, description]) => <label key={key} className="rounded-2xl border border-[#172554]/10 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><span className="text-sm font-bold text-[#172554]">{label}</span><p className="mt-1 text-xs text-[#71838d]">{description}</p></div><output className="rounded-lg bg-[#eef4ff] px-2 py-1 text-xs font-bold text-[#065be5]">{studioWidths[key]} px</output></div><input type="range" min="760" max="1440" step="40" value={studioWidths[key]} onChange={event => setStudioWidths(current => ({ ...current, [key]: Number(event.target.value) }))} aria-label={`Chiều rộng ${label}`} className="mt-5 h-2 w-full cursor-pointer accent-[#065be5]" /><div className="mt-2 flex justify-between text-[10px] font-semibold text-[#8a95a5]"><span>760 px</span><span>1.440 px</span></div></label>)}</div></section><div className="mt-6 flex flex-wrap gap-3"><Button onClick={save} disabled={saveMutation.isPending} className="cta-gradient rounded-full">{saveMutation.isPending ? "Đang lưu…" : "Lưu thay đổi"}</Button><Button variant="outline" onClick={reset} className="rounded-full">Khôi phục mặc định</Button></div></section>;
}
