import CategoryCoverSettings from "@/components/CategoryCoverSettings";
import { CPanelPageHeader } from "@/components/CPanelPageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, ChevronRight, Layers3, Loader2, Plus, Save, Sparkles } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

type ContentKind = "category" | "subject" | "lesson";
const kindLabel: Record<ContentKind, string> = { category: "Chủ đề", subject: "Môn học", lesson: "Bài học" };
const slugify = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || `muc-${Date.now()}`;

export default function ContentManagementPanel() {
  const content = trpc.admin.contentTree.useQuery();
  const saveNode = trpc.admin.saveContentNode.useMutation({ onSuccess: () => { content.refetch(); toast.success("Đã lưu cấu trúc nội dung."); }, onError: error => toast.error("Không thể lưu cấu trúc nội dung", { description: error.message }) });
  const saveQuiz = trpc.admin.saveQuiz.useMutation({ onSuccess: () => { content.refetch(); toast.success("Đã lưu bộ đề."); }, onError: error => toast.error("Không thể lưu bộ đề", { description: error.message }) });
  const [kind, setKind] = useState<ContentKind>("category"); const [nodeTitle, setNodeTitle] = useState(""); const [nodeParent, setNodeParent] = useState(""); const [quizTitle, setQuizTitle] = useState(""); const [quizLesson, setQuizLesson] = useState(""); const [quizMode, setQuizMode] = useState<"training" | "testing">("training");
  const counts = useMemo(() => ({ categories: content.data?.categories.length ?? 0, subjects: content.data?.subjects.length ?? 0, lessons: content.data?.lessons.length ?? 0, quizzes: content.data?.quizzes.length ?? 0 }), [content.data]);
  const parentLabel = kind === "subject" ? "ID Chủ đề" : "ID Môn học";
  const handleNode = (event: FormEvent) => { event.preventDefault(); saveNode.mutate({ kind, title: nodeTitle, slug: slugify(nodeTitle), parentId: kind === "category" ? undefined : Number(nodeParent), isPublished: true, sortOrder: 0 }); };
  const handleQuiz = (event: FormEvent) => { event.preventDefault(); saveQuiz.mutate({ lessonId: Number(quizLesson), title: quizTitle, slug: slugify(quizTitle), mode: quizMode, accessTier: "basic", durationSeconds: 900, passingScore: 70, entryPointCost: quizMode === "testing" ? 20 : 0, completionReward: quizMode === "testing" ? 40 : 0, isPublished: true }); };

  return <div className="mx-auto max-w-[1440px]"><CPanelPageHeader eyebrow="Learning / Content architecture" title="Nội dung học tập" description="Quản lý Chủ đề, Môn học, Bài học và bộ đề theo cấu trúc bốn cấp nhất quán." actions={<Button asChild className="rounded-[var(--radius-md-token)]"><a href="/tao-quiz"><Sparkles size={16} />Tạo Quiz trong Studio</a></Button>} />
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{([{ label: "Chủ đề", value: counts.categories, icon: Layers3 }, { label: "Môn học", value: counts.subjects, icon: BookOpenCheck }, { label: "Bài học", value: counts.lessons, icon: Layers3 }, { label: "Bộ đề", value: counts.quizzes, icon: BookOpenCheck }]).map(({ label, value, icon: Icon }) => <div key={label} className="rounded-[var(--radius-lg-token)] border border-border bg-surface p-4"><Icon size={18} className="text-primary" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.13em] text-text-muted">{label}</p><p className="mt-1 text-2xl font-bold text-foreground">{content.isLoading ? "—" : value}</p></div>)}</section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><form onSubmit={handleNode} className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Create content node</p><h2 className="mt-2 text-2xl font-bold text-foreground">Thêm vào lộ trình</h2><p className="mt-2 text-sm leading-6 text-text-secondary">Tạo cấp nội dung trước khi gắn bài học và bộ đề.</p><div className="mt-6 grid grid-cols-3 gap-2">{(["category", "subject", "lesson"] as const).map(item => <button type="button" key={item} onClick={() => setKind(item)} className={`rounded-[var(--radius-sm-token)] px-2 py-3 text-[11px] font-bold transition-colors ${kind === item ? "bg-primary text-primary-foreground" : "bg-muted text-text-secondary hover:text-foreground"}`}>{kindLabel[item]}</button>)}</div><div className="mt-5 space-y-4"><div><Label>Tên {kindLabel[kind]}</Label><Input value={nodeTitle} onChange={event => setNodeTitle(event.target.value)} required className="mt-1.5" placeholder={`Ví dụ: ${kind === "category" ? "Lập trình" : kind === "subject" ? "Python cơ bản" : "Biến và kiểu dữ liệu"}`} /></div>{kind !== "category" ? <div><Label>{parentLabel}</Label><Input value={nodeParent} onChange={event => setNodeParent(event.target.value)} required type="number" className="mt-1.5" placeholder="Chọn từ cây nội dung hiện có" /></div> : null}</div><Button disabled={saveNode.isPending} className="mt-6 w-full rounded-[var(--radius-md-token)]">{saveNode.isPending ? <Loader2 className="animate-spin" size={15} /> : <Plus size={15} />}Tạo {kindLabel[kind]}</Button></form>
      <section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Content tree</p><h2 className="mt-2 text-2xl font-bold text-foreground">Cấu trúc đã tạo</h2></div><Badge variant="secondary" className="rounded-full bg-primary-light text-primary">{counts.quizzes} bộ đề</Badge></div>{content.isLoading ? <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : content.data?.categories.length ? <div className="mt-5 space-y-3">{content.data.categories.map(category => <div key={category.id} className="rounded-[var(--radius-md-token)] border border-border bg-muted p-4"><div className="flex flex-wrap items-center gap-2"><Badge className="rounded-full bg-primary text-primary-foreground">Chủ đề</Badge><p className="font-semibold text-foreground">{category.title}</p><span className="font-mono text-[10px] text-text-muted">#{category.id}</span></div><div className="mt-4 space-y-3 border-l border-primary/25 pl-4">{content.data.subjects.filter(subject => subject.categoryId === category.id).map(subject => <div key={subject.id}><div className="flex items-center gap-2"><ChevronRight size={14} className="text-primary" /><p className="text-sm font-semibold text-foreground">{subject.title}</p><span className="font-mono text-[10px] text-text-muted">#{subject.id}</span></div><div className="mt-2 space-y-2 border-l border-border pl-4">{content.data.lessons.filter(lesson => lesson.subjectId === subject.id).map(lesson => <div key={lesson.id} className="flex items-center gap-2 text-xs text-text-secondary"><BookOpenCheck size={13} className="text-primary" />{lesson.title}<span className="font-mono text-[10px] text-text-muted">#{lesson.id}</span></div>)}{!content.data.lessons.some(lesson => lesson.subjectId === subject.id) ? <p className="text-xs text-text-muted">Chưa có bài học.</p> : null}</div></div>)}{!content.data.subjects.some(subject => subject.categoryId === category.id) ? <p className="text-xs text-text-muted">Chưa có môn học.</p> : null}</div></div>)}</div> : <EmptyContentTree />}</section></section>
    <form onSubmit={handleQuiz} className="mt-6 rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-end"><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Create Quiz</p><h2 className="mt-2 text-2xl font-bold text-foreground">Tạo bộ đề trong lộ trình</h2><p className="mt-2 text-sm text-text-secondary">Quiz được gắn trực tiếp vào Bài học trước khi biên soạn chi tiết trong Studio.</p></div><div className="grid flex-[2] gap-3 sm:grid-cols-3"><div><Label>Tên bộ đề</Label><Input value={quizTitle} onChange={event => setQuizTitle(event.target.value)} required className="mt-1.5" placeholder="Ví dụ: Kiểm tra chương 01" /></div><div><Label>ID Bài học</Label><Input value={quizLesson} onChange={event => setQuizLesson(event.target.value)} required type="number" className="mt-1.5" placeholder="Bắt buộc" /></div><div><Label>Hình thức</Label><select value={quizMode} onChange={event => setQuizMode(event.target.value as "training" | "testing")} className="mt-1.5 h-10 w-full rounded-[var(--radius-sm-token)] border border-input bg-surface px-3 text-sm"><option value="training">Ôn tập</option><option value="testing">Kiểm tra</option></select></div></div><Button disabled={saveQuiz.isPending} className="rounded-[var(--radius-md-token)]">{saveQuiz.isPending ? <Loader2 className="animate-spin" size={15} /> : <Save size={15} />}Lưu bộ đề</Button></div></form><div className="mt-6"><CategoryCoverSettings /></div></div>;
}

function EmptyContentTree() { return <div className="mt-5 grid min-h-56 place-items-center rounded-[var(--radius-md-token)] bg-muted p-6 text-center"><div><Layers3 className="mx-auto text-primary" size={24} /><p className="mt-3 text-sm font-bold text-foreground">Chưa có cấu trúc nội dung</p><p className="mt-1 text-xs leading-5 text-text-secondary">Bắt đầu với một Chủ đề, sau đó thêm Môn học, Bài học và bộ đề.</p></div></div>; }
