import { CPanelPageHeader } from "@/components/CPanelPageHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, Clock3, Loader2, RefreshCw, Timer } from "lucide-react";

const elapsed = (startedAt: Date) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(startedAt).getTime()) / 60000)); return minutes < 1 ? "Vừa bắt đầu" : `${minutes} phút`; };

export default function LiveMonitoringPanel() {
  const monitoring = trpc.admin.liveMonitoring.useQuery(undefined, { refetchInterval: 10_000 });
  if (monitoring.isLoading) return <div className="mx-auto grid min-h-64 max-w-[1440px] place-items-center" role="status"><span className="flex items-center gap-2 text-sm text-text-secondary"><Loader2 className="animate-spin text-primary" />Đang mở System monitoring…</span></div>;
  if (monitoring.error) return <div className="mx-auto max-w-[1440px] rounded-[var(--radius-lg-token)] border border-danger/25 bg-danger/5 p-6 text-sm text-danger" role="alert"><strong>Chưa tải được hoạt động trực tiếp.</strong><p className="mt-1">{monitoring.error.message}</p><Button onClick={() => monitoring.refetch()} className="mt-4 rounded-[var(--radius-md-token)]"><RefreshCw size={15} />Thử lại</Button></div>;
  const data = monitoring.data;
  return <div className="mx-auto max-w-[1440px]"><CPanelPageHeader eyebrow="System / Live monitoring" title="Live Monitoring" description="Theo dõi lượt thi đang diễn ra và hoạt động trong 60 phút gần nhất. Dữ liệu tự làm mới mỗi 10 giây." actions={<Button variant="outline" onClick={() => monitoring.refetch()} className="rounded-[var(--radius-md-token)]"><RefreshCw size={15} className={monitoring.isFetching ? "animate-spin" : ""} />Làm mới</Button>} />
    <section className="mt-6 grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]"><div className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><span className="grid size-11 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Activity size={20} /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.15em] text-text-muted">Active Quiz Sessions</p><p className="mt-2 text-5xl font-bold tracking-[-.05em] text-foreground">{data?.active.length ?? 0}</p><p className="mt-2 text-sm leading-6 text-text-secondary">Lượt thi đang mở tại thời điểm làm mới gần nhất.</p><p className="mt-7 flex items-center gap-2 text-[11px] text-text-muted"><Clock3 size={14} />Cập nhật {data?.refreshedAt ? new Date(data.refreshedAt).toLocaleTimeString("vi-VN") : "—"}</p></div>
      <section className="rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">Active now</p><h2 className="mt-2 text-2xl font-bold text-foreground">Phiên đang làm Quiz</h2></div><span className="grid size-10 place-items-center rounded-[var(--radius-md-token)] bg-primary-light text-primary"><Timer size={18} /></span></div>{data?.active.length ? <div className="mt-5 overflow-hidden rounded-[var(--radius-md-token)] border border-border"><div className="hidden grid-cols-[1fr_1fr_140px] gap-4 bg-muted px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-text-muted sm:grid"><span>Người học</span><span>Quiz</span><span>Thời gian</span></div>{data.active.map(row => <div key={row.attempt.id} className="grid gap-1 border-t border-border-light px-4 py-4 sm:grid-cols-[1fr_1fr_140px] sm:items-center sm:gap-4"><div><p className="text-sm font-semibold text-foreground">{row.learnerName ?? row.learnerEmail ?? "Học viên"}</p><p className="mt-1 text-xs text-text-secondary sm:hidden">{row.quizTitle}</p></div><p className="hidden truncate text-sm text-text-secondary sm:block">{row.quizTitle}</p><span className="w-fit rounded-full bg-primary-light px-3 py-1 text-[10px] font-bold text-primary">{elapsed(row.attempt.startedAt)}</span></div>)}</div> : <EmptyState message="Chưa có lượt thi nào đang diễn ra. Bảng sẽ tự cập nhật khi học viên bắt đầu làm bài." />}</section></section>
    <section className="mt-6 rounded-[var(--radius-xl-token)] border border-border bg-surface p-6"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">Recent activity</p><h2 className="mt-2 text-2xl font-bold text-foreground">Lượt thi vừa kết thúc</h2>{data?.recent.length ? <div className="mt-5 divide-y divide-border-light">{data.recent.map(row => <div key={row.attempt.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-foreground">{row.learnerName ?? row.learnerEmail ?? "Học viên"}</p><p className="mt-1 text-xs text-text-secondary">{row.quizTitle}</p></div><span className="w-fit rounded-full bg-muted px-3 py-1 text-[10px] font-bold text-text-secondary">{row.attempt.status === "submitted" ? "Đã nộp bài" : row.attempt.status}</span></div>)}</div> : <EmptyState message="Chưa có hoạt động kết thúc trong 60 phút gần nhất." />}</section>
    <section className="mt-6 rounded-[var(--radius-lg-token)] border border-info/15 bg-info/5 p-5 text-xs leading-6 text-info"><strong>Phạm vi dữ liệu hiện tại.</strong> System monitoring đã hiển thị phiên Quiz thực. Các chỉ số request, AI jobs, queue, errors và system health sẽ được bổ sung khi backend phát hành telemetry tương ứng; dashboard không mô phỏng các chỉ số này.</section></div>;
}

function EmptyState({ message }: { message: string }) { return <div className="mt-5 rounded-[var(--radius-md-token)] bg-muted p-5 text-sm leading-6 text-text-secondary">{message}</div>; }
