import AuthActionLink from "@/components/AuthActionLink";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ShowcaseQuiz } from "@/data/demo";
import { getQuizDifficultyTone } from "@/lib/quizDifficulty";
import { ROUTES } from "@/lib/routes";
import { cn } from "@/lib/utils";
import { Award, Clock3, FileQuestion, Play, UsersRound } from "lucide-react";

export default function QuizCard({ quiz }: { quiz: ShowcaseQuiz; compact?: boolean }) {
  const difficulty = getQuizDifficultyTone(quiz.difficulty);
  const topic = quiz.topicPath || [quiz.category, quiz.subject].filter(Boolean).join(" › ");
  const tierClass = quiz.tier === "Premium" ? "bg-violet-600 text-white" : quiz.tier === "Pro" ? "bg-sky-600 text-white" : "bg-emerald-600 text-white";
  return <article className="group flex min-w-0 gap-4 rounded-2xl border border-border bg-white p-4 shadow-sm transition-[border-color,box-shadow,transform] duration-200 hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md dark:bg-card sm:gap-5"><div className="relative size-28 shrink-0 overflow-hidden rounded-[18px] bg-primary-light sm:size-32">{quiz.coverImage ? <img src={quiz.coverImage} alt={`Ảnh bìa ${quiz.title}`} className="size-full object-cover transition-transform duration-200 group-hover:scale-105" /> : <span className="grid size-full place-items-center text-primary/45"><FileQuestion size={34} /></span>}<Badge className={cn("absolute right-2 top-2 border-0 px-2 py-1 text-[9px] font-extrabold uppercase shadow-sm", tierClass)}>{quiz.tier}</Badge></div><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold text-primary" title={topic}>{topic || "Chủ đề chưa phân loại"}</p><h3 className="mt-1.5 line-clamp-2 text-base font-extrabold leading-snug text-foreground transition-colors group-hover:text-primary sm:text-lg">{quiz.title}</h3><p className="mt-1 text-xs font-medium text-text-secondary">Tác giả Quiz</p><div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-2 text-[11px] font-semibold text-text-secondary"><span className={cn("inline-flex items-center gap-1 rounded-full px-2 py-1", difficulty.badgeClass)}><i className={cn("size-1.5 rounded-full", difficulty.dotClass)} />{difficulty.label}</span><span className="inline-flex items-center gap-1"><Clock3 size={13} />{quiz.duration}</span><span className="inline-flex items-center gap-1"><FileQuestion size={13} />{quiz.questionCount} câu</span><span className="inline-flex items-center gap-1"><UsersRound size={13} />{typeof quiz.attemptCount === "number" ? quiz.attemptCount.toLocaleString("vi-VN") : 0} lượt</span><span className="inline-flex items-center gap-1 text-success"><Award size={13} />+{quiz.reward} Point</span></div></div><Button asChild size="icon" className="mt-auto shrink-0 rounded-full cta-gradient sm:mt-7" aria-label={`Làm bài ${quiz.title}`}><AuthActionLink href={`${ROUTES.quiz}/${quiz.id}`}><Play size={15} fill="currentColor" /></AuthActionLink></Button></article>;
}
