import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Braces, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";

export function QuizDraftAiTools({ question, onEnhanced }: { question: any; onEnhanced: (change: any) => void }) {
  const enhance = trpc.creator.enhanceQuestionAI.useMutation({ onSuccess: result => { onEnhanced({ prompt: result.prompt, explanation: result.explanation, options: result.options, accepted: Array.isArray(result.answerConfig?.acceptedAnswers) ? result.answerConfig.acceptedAnswers.join("|") : undefined, pairs: Array.isArray(result.answerConfig?.pairs) ? result.answerConfig.pairs : undefined, outline: typeof result.answerConfig?.sampleOutline === "string" ? result.answerConfig.sampleOutline : undefined }); toast.success("AI đã cập nhật bản nháp câu hỏi."); }, onError: error => toast.error("Không thể dùng công cụ AI", { description: error.message }) });
  const run = (action: "explain" | "rephrase" | "latex") => { if (!question.prompt?.trim() || question.prompt.trim().length < 8) return toast.error("Hãy nhập câu hỏi trước khi dùng AI hỗ trợ."); const answerConfig = question.type === "fill_blank" ? { acceptedAnswers: String(question.accepted || "").split("|").map((value: string) => value.trim()).filter(Boolean) } : question.type === "matching" ? { pairs: question.pairs ?? [] } : question.type === "essay" ? { sampleOutline: question.outline ?? "" } : {}; enhance.mutate({ action, question: { type: question.type, difficulty: question.difficulty, prompt: question.prompt, explanation: question.explanation ?? "", options: question.options ?? [], answerConfig } }); };
  const disabled = enhance.isPending || !question.prompt?.trim();
  return <section className="rounded-2xl border border-[#7057e8]/18 bg-[#fbfaff] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#f0eaff] text-[#7057e8]"><Sparkles size={15} /></span><div><p className="text-xs font-bold text-[#172554]">AI hỗ trợ câu hỏi đang soạn</p><p className="mt-0.5 text-[10px] text-[#71838d]">Kết quả được đưa thẳng vào bản nháp để bạn xem và chỉnh sửa.</p></div></div>{enhance.isPending ? <span className="inline-flex items-center gap-1 text-[10px] font-bold text-[#7057e8]"><Loader2 size={13} className="animate-spin" />Đang xử lý</span> : null}</div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => run("explain")} disabled={disabled} className="h-8 rounded-full border-[#7057e8]/20 bg-white text-[11px] text-[#7057e8]"><Sparkles size={13} />Tạo lời giải</Button><Button type="button" variant="outline" onClick={() => run("rephrase")} disabled={disabled} className="h-8 rounded-full border-[#7057e8]/20 bg-white text-[11px] text-[#7057e8]"><RefreshCw size={13} />Biến đổi câu hỏi</Button><Button type="button" variant="outline" onClick={() => run("latex")} disabled={disabled} className="h-8 rounded-full border-[#7057e8]/20 bg-white text-[11px] text-[#7057e8]"><Braces size={13} />Chuẩn hóa LaTeX</Button></div></section>;
}
