import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowUpDown, Download, Filter, LockKeyhole, Search, ShieldCheck, UserCog, UsersRound, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type SortMode = "name" | "newest" | "completed";

const initials = (name?: string | null) => (name ?? "U").trim().split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase() || "U";
const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function UserManagementPanel() {
  const [search, setSearch] = useState("");
  const [tier, setTier] = useState<"all" | "basic" | "pro" | "premium">("all");
  const [status, setStatus] = useState<"all" | "active" | "banned">("all");
  const [sort, setSort] = useState<SortMode>("name");
  const query = trpc.admin.users.useQuery({ search: search || undefined, tier: tier === "all" ? undefined : tier, status: status === "all" ? undefined : status });
  const updateTier = trpc.admin.updateUserTier.useMutation({ onSuccess: () => { query.refetch(); toast.success("Đã cập nhật hạng thành viên."); }, onError: error => toast.error("Không thể cập nhật hạng", { description: error.message }) });
  const updateStatus = trpc.admin.updateUserStatus.useMutation({ onSuccess: () => { query.refetch(); toast.success("Đã cập nhật trạng thái tài khoản."); }, onError: error => toast.error("Không thể cập nhật trạng thái", { description: error.message }) });
  const adjust = trpc.admin.adjustPoints.useMutation({ onSuccess: result => { query.refetch(); toast.success(`Đã điều chỉnh Point. Số dư mới: ${result.balanceAfter}.`); }, onError: error => toast.error("Không thể điều chỉnh Point", { description: error.message }) });

  const rows = useMemo(() => [...(query.data ?? [])].sort((left, right) => {
    if (sort === "completed") return right.completedCount - left.completedCount;
    if (sort === "newest") return new Date(right.user.createdAt).getTime() - new Date(left.user.createdAt).getTime();
    return (left.user.name ?? left.user.email ?? left.user.openId).localeCompare(right.user.name ?? right.user.email ?? right.user.openId, "vi");
  }), [query.data, sort]);
  const adjustPoints = (userId: number) => { const amount = Number(window.prompt("Số Point điều chỉnh (dương để cộng, âm để trừ):")); if (!Number.isInteger(amount) || amount === 0) return; const description = window.prompt("Lý do điều chỉnh Point:"); if (!description?.trim()) return; adjust.mutate({ userId, amount, description }); };
  const exportUsers = () => {
    const content = ["Họ tên,Email,Hạng,Point,Lượt hoàn thành,Trạng thái", ...rows.map(row => [row.user.name ?? "", row.user.email ?? row.user.openId, row.profile?.tier ?? "basic", row.profile?.pointBalance ?? 0, row.completedCount, row.profile?.isBanned ? "Đã khóa" : "Hoạt động"].map(csvCell).join(","))].join("\n");
    const url = URL.createObjectURL(new Blob(["\ufeff", content], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = "dshare-user-list.csv"; anchor.click(); URL.revokeObjectURL(url);
    toast.success("Đã xuất danh sách người dùng.");
  };

  return <div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-5 border-b border-[#172554]/10 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#065be5]">Dshare / Quản trị / Người dùng</p><h1 className="mt-2 font-serif text-[36px] font-semibold tracking-[-.045em] text-[#172554]">Người dùng</h1><p className="mt-2 text-sm text-[#617786]">Tra cứu, sắp xếp và quản lý nhanh hồ sơ thành viên trong một danh sách tập trung.</p></div><div className="flex flex-wrap gap-2"><Button onClick={exportUsers} disabled={!rows.length} className="rounded-full bg-[#065be5]"><Download size={15} /> Xuất danh sách</Button><Button asChild variant="outline" className="rounded-full border-[#065be5]/20 bg-white text-[#065be5]"><a href="/quan-tri/nhom-nguoi-dung"><UserCog size={15} /> Gán vào nhóm</a></Button></div></div>
    <section className="mt-6 overflow-hidden rounded-[26px] border border-[#172554]/10 bg-white shadow-sm"><div className="border-b border-[#172554]/8 bg-[#f8fbff] p-4"><div className="grid gap-3 lg:grid-cols-[1.4fr_.75fr_.75fr_.75fr]"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#71838d]" size={16} /><Input value={search} onChange={event => setSearch(event.target.value)} className="h-10 border-[#172554]/10 bg-white pl-9 text-sm" placeholder="Tìm theo tên hoặc email…" aria-label="Tìm người dùng" /></label><label className="flex items-center gap-2 rounded-md border border-[#172554]/10 bg-white px-3 text-xs text-[#617786]"><Filter size={14} /><select value={tier} onChange={event => setTier(event.target.value as typeof tier)} aria-label="Lọc hạng thành viên" className="h-8 min-w-0 flex-1 bg-transparent outline-none"><option value="all">Mọi gói</option><option value="basic">Basic</option><option value="pro">PRO</option><option value="premium">PREMIUM</option></select></label><label className="flex items-center gap-2 rounded-md border border-[#172554]/10 bg-white px-3 text-xs text-[#617786]"><ShieldCheck size={14} /><select value={status} onChange={event => setStatus(event.target.value as typeof status)} aria-label="Lọc trạng thái" className="h-8 min-w-0 flex-1 bg-transparent outline-none"><option value="all">Mọi trạng thái</option><option value="active">Hoạt động</option><option value="banned">Đã khóa</option></select></label><label className="flex items-center gap-2 rounded-md border border-[#172554]/10 bg-white px-3 text-xs text-[#617786]"><ArrowUpDown size={14} /><select value={sort} onChange={event => setSort(event.target.value as SortMode)} aria-label="Sắp xếp danh sách người dùng" className="h-8 min-w-0 flex-1 bg-transparent outline-none"><option value="name">Tên A–Z</option><option value="newest">Mới tham gia</option><option value="completed">Lượt làm nhiều</option></select></label></div></div>
      <div className="flex items-center justify-between px-5 py-3 text-[11px] text-[#71838d]"><span>{query.isLoading ? "Đang tải danh sách…" : `${rows.length} người dùng phù hợp`}</span><span className="hidden sm:inline">Chọn hạng, Point hoặc trạng thái để quản lý nhanh</span></div>
      <div className="hidden grid-cols-[minmax(260px,1.8fr)_120px_100px_120px_190px] gap-4 border-y border-[#172554]/8 bg-[#eef4ff] px-5 py-3 text-[10px] font-bold uppercase tracking-[.13em] text-[#71838d] lg:grid"><span>Thành viên</span><span>Gói</span><span>Point</span><span>Lượt làm</span><span>Thao tác</span></div>
      {query.isLoading ? <p className="p-10 text-center text-sm text-[#71838d]">Đang tải danh sách thành viên…</p> : rows.length ? <div>{rows.map((row, index) => { const displayName = row.user.name ?? "Chưa đặt tên"; const email = row.user.email ?? row.user.openId; const tierValue = row.profile?.tier ?? "basic"; return <article key={row.user.id} className="border-b border-[#172554]/7 px-5 py-4 last:border-b-0"><div className="grid gap-4 lg:grid-cols-[minmax(260px,1.8fr)_120px_100px_120px_190px] lg:items-center"><div className="flex min-w-0 items-center gap-3"><Avatar className="h-11 w-11 rounded-xl border border-white shadow-sm"><AvatarImage src={row.profile?.avatarUrl ?? undefined} alt="" /><AvatarFallback className="rounded-xl text-sm font-bold" style={{ backgroundColor: ["#d7f4f1", "#dbeafe", "#fef3c7", "#fce7f3"][index % 4], color: "#172554" }}>{initials(displayName)}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-bold text-[#172554]">{displayName}</p><p className="mt-1 truncate text-[11px] text-[#71838d]">{email}</p></div>{row.profile?.isBanned ? <span className="rounded-full bg-[#fff0f6] px-2 py-1 text-[9px] font-bold text-[#de1264]">Đã khóa</span> : null}</div><div><select value={tierValue} onChange={event => updateTier.mutate({ userId: row.user.id, tier: event.target.value as "basic" | "pro" | "premium" })} aria-label={`Hạng của ${displayName}`} className="h-8 rounded-full border border-[#065be5]/15 bg-[#eef4ff] px-2.5 text-[10px] font-bold text-[#065be5]"><option value="basic">Basic</option><option value="pro">PRO</option><option value="premium">PREMIUM</option></select></div><div className="flex items-center gap-1.5 font-mono text-xs font-bold text-[#d97706]"><WalletCards size={13} /> {row.profile?.pointBalance ?? 0}</div><div className="flex items-center gap-1.5 text-xs text-[#617786]"><UsersRound size={13} /> {row.completedCount}</div><div className="flex flex-wrap gap-1.5"><Button onClick={() => adjustPoints(row.user.id)} variant="outline" className="h-8 rounded-full bg-white px-3 text-[10px]"><WalletCards size={12} /> Point</Button><Button onClick={() => updateStatus.mutate({ userId: row.user.id, isBanned: !(row.profile?.isBanned ?? false) })} variant="outline" className={`h-8 rounded-full px-3 text-[10px] ${row.profile?.isBanned ? "border-[#007453]/25 text-[#007453]" : "border-[#de1264]/20 text-[#de1264]"}`}>{row.profile?.isBanned ? "Mở khóa" : "Khóa"}</Button></div></div></article>; })}</div> : <div className="p-12 text-center"><UsersRound className="mx-auto text-[#71838d]" size={28} /><p className="mt-3 text-sm font-bold text-[#172554]">Không tìm thấy người dùng phù hợp</p><p className="mt-1 text-xs text-[#71838d]">Hãy điều chỉnh từ khóa hoặc bộ lọc để xem lại danh sách.</p></div>}
    </section>
  </div>;
}
